const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.stack));page.on('request',r=>requests.push(r.url()));
 await page.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));await page.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));
 const out=process.env.VOID_SCREENSHOT_DIR;if(out)fs.mkdirSync(out,{recursive:true});
 async function snap(name){if(out)await page.screenshot({path:path.join(out,name+'.png')});}
 try{
  await page.goto('http://127.0.0.1:5000/void-runner.html?renderer=babylon');await page.waitForFunction(()=>window.VoidStartup?.started);
  assert(!requests.some(u=>u.includes('/vendor/')),'engine must not download at menu boot');
  await page.evaluate(async()=>{state=C.fresh();C.beginJourney(state);await launch();});assert.equal(await page.evaluate(()=>mode),'play');
  const departure=await page.evaluate(()=>{mode='pause';flight.route.departure=.2;draw();return {ready:VoidBabylon.diagnostics.exteriorReady,meshes:VoidBabylon.scene.meshes.map(m=>m.name),clock:flight.route.departure};});assert(departure.ready);assert(departure.meshes.includes('planet'));assert(departure.meshes.includes('asteroid'));assert(departure.meshes.includes('central-spine'));await snap('departure');
  const projection=await page.evaluate(()=>{flight.yaw=.7;flight.pitch=.3;flight.roll=.4;draw();const camera=VoidBabylon.scene.activeCamera;const errors=[{x:60,y:20,z:90},{x:10,y:-10,z:50}].map(v=>{const actual=BABYLON.Vector3.Project(new BABYLON.Vector3(v.x,-v.y,v.z),BABYLON.Matrix.Identity(),camera.getTransformationMatrix(),new BABYLON.Viewport(0,0,W,H)),expected=flightPoint(v);return Math.hypot(actual.x-expected.x,actual.y-expected.y);});flight.yaw=flight.pitch=flight.roll=0;return errors;});assert(projection.every(e=>e<.01),'Babylon objects must agree with lock/HUD projection');
  const marker=await page.evaluate(()=>{mode='play';flight.route.phase='align';flight.yaw=0;VoidNavigationReveal.reset(navigationReveal,'align');for(let i=0;i<49;i++)update(.04);const early=VoidNavigationReveal.opacity(navigationReveal);for(let i=0;i<12;i++)update(.04);const later=VoidNavigationReveal.opacity(navigationReveal);mode='pause';draw();return {early,later};});assert.equal(marker.early,0);assert(marker.later>.9);await snap('space');
  const controls=await page.evaluate(()=>{mode='play';flight.route=null;const before={yaw:flight.yaw,pitch:flight.pitch,roll:flight.roll,throttle:flight.throttle};VoidInput.held.add('KeyD');VoidInput.held.add('KeyS');VoidInput.held.add('KeyR');VoidInput.held.add('ShiftLeft');for(let i=0;i<20;i++)update(.04);clearInput();mode='pause';return {before,after:{yaw:flight.yaw,pitch:flight.pitch,roll:flight.roll,throttle:flight.throttle},speed:FM.length(flight.velocity)};});assert(controls.after.yaw>controls.before.yaw);assert(controls.after.pitch>controls.before.pitch);assert(controls.after.roll>controls.before.roll);assert(controls.after.throttle>controls.before.throttle);assert(controls.speed>0);
  const combat=await page.evaluate(()=>{mode='play';flight.yaw=flight.pitch=flight.roll=0;flight.velocity={x:0,y:0,z:0};flight.route=VoidWarp.create('meridian','kepler','test',true);flight.route.phase='encounter';current.enemies=1;spawned=1;resolved=0;enemies=[{x:0,y:0,z:48,size:1,armor:4,maxArmor:4,shield:0,maxShield:0,age:0,phase:0,fire:99,className:'raider',velocity:{x:0,y:0,z:0}}];state.creditGear.push('launcher');state.loadout.missile='launcher';resetMissileFlight();for(let i=0;i<120;i++)VoidTargeting.step(missileLock,enemies,flightPoint,W,H,.04,missileBalance(),true);const lock=missileLock.progress;fireMissile();const launched=missiles.length;for(let i=0;i<100&&missiles.length;i++)stepMissileCombat(.02,{x:0,y:0,z:0});const killed=enemies[0].dead;enemies=enemies.filter(e=>!e.dead);update(.04);const reveal=VoidNavigationReveal.opacity(navigationReveal),phase=flight.route.phase;mode='pause';draw();return {lock,launched,killed,reveal,phase,clouds:VoidCombatEffects.clouds.length};});assert.equal(combat.lock,1);assert.equal(combat.launched,1);assert(combat.killed);assert.equal(combat.phase,'align');assert.equal(combat.reveal,0);assert(combat.clouds>0);await snap('missile-impact');
  await page.evaluate(async()=>{mode='dock';state.quest='legal-offer';await enterWalking('hangar');});assert.equal(await page.evaluate(()=>mode),'walking');await snap('hangar');
  const moved=await page.evaluate(()=>{const start=walker.z;walkingKeys.add('KeyW');for(let i=0;i<80;i++)update(.04);walkingKeys.clear();return {start,z:walker.z};});assert(moved.z>moved.start+7);
  await page.evaluate(()=>{walker.x=3;walker.z=2;walker.yaw=0;update(.01);});await page.keyboard.press('e');assert.equal(await page.evaluate(()=>mode),'dialogue');assert.match(await page.locator('.speaker').textContent(),/Rook/);await page.locator('[data-action=walk-resume]').click();assert.equal(await page.evaluate(()=>mode),'walking');
  await page.evaluate(()=>{walker.x=-3;walker.z=-12;walker.yaw=0;update(.01);});await page.keyboard.press('e');assert.equal(await page.evaluate(()=>mode),'dock');
  const sceneCounts=[];
  for(const id of ['sacramento','mars-terminal','sacramento','mars-terminal']){await page.evaluate(async id=>{state.quest='open';await enterWalking(id);},id);assert.equal(await page.evaluate(()=>mode),'walking');sceneCounts.push(await page.evaluate(()=>({meshes:VoidBabylon.scene.meshes.length,textures:VoidBabylon.scene.textures.length})));await snap(id);}
  assert.equal(sceneCounts[0].meshes,sceneCounts[2].meshes);assert.equal(sceneCounts[1].meshes,sceneCounts[3].meshes);assert.equal(sceneCounts[1].textures,sceneCounts[3].textures);
  await page.evaluate(async()=>{await leaveWalking();});
  for(const id of ['earth','mars']){await page.evaluate(async id=>{state.quest='open';state.contract=null;await solTravel(id);expedition.pilot.yaw=Math.atan2(expedition.vector.x,expedition.vector.z);for(let i=0;i<300&&mode==='transit3d';i++)update(.04);},id);assert.equal(await page.evaluate(()=>view),'orbit');assert.equal(await page.evaluate(()=>state.story.flags.solDestination),id);}
  const restored=await page.evaluate(()=>C.restore(localStorage.getItem(SAVE_KEY)));assert.equal(restored.quest,'open');assert.equal(restored.story.flags.solDestination,'mars');
  for(const origin of ['meridian','kepler','undertow','foundry']){const prepared=await page.evaluate(async origin=>{state=C.fresh();state.quest='open';state.location=origin;C.chooseDestination(state,origin==='meridian'?'kepler':'meridian');await launch();mode='pause';draw();return {ready:VoidBabylon.diagnostics.exteriorReady,location:VoidBabylon.diagnostics.location,art:departureImages[origin].naturalWidth};},origin);assert(prepared.ready&&prepared.art>0);assert.equal(prepared.location,origin);}
  const escort=await page.evaluate(async()=>{VoidGraphics.renderer='babylon';state.quest='open';state.contract='belt-3';state.location='kepler';await launch();flight.route.phase='encounter';const friendly=enemies.filter(e=>!VoidStory.hostile(e)).length;escortImpact({escort:true,damage:10});const health=escortShip.health;spawned=resolved=current.enemies;enemies=[];flight.velocity={x:0,y:0,z:0};for(let i=0;i<10;i++)update(.04);const progress=escortShip.progress;escortShip.z=200;VoidEscort.step(escortShip,.1,flight.velocity,flightBasis().f,false);const status=escortShip.status;escortShip.z=38;escortShip.progress=1;elapsed=current.duration;approachTime=VoidWarp.config.approachSeconds;flight.route.phase='arrived';arrive();const completedStatus=escortShip.status;mode='pause';return {friendly,health,progress,status,completedStatus};});assert.equal(escort.friendly,0);assert.equal(escort.health,90);assert(escort.progress>0);assert.equal(escort.status,'waiting');assert.equal(escort.completedStatus,'complete');
  await page.evaluate(()=>settingsPage());await page.locator('#quality-setting').selectOption('low');await page.locator('#renderer-setting').selectOption('legacy');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('void-runner-graphics-v1')).quality),'low');
  const flask=await browser.newPage();flask.on('pageerror',e=>errors.push(e.stack));await flask.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));await flask.goto('http://127.0.0.1:5001/void-runner.html?renderer=babylon');await flask.waitForFunction(()=>window.VoidStartup?.started);assert(await flask.evaluate(async()=>{state=C.fresh();C.beginJourney(state);await launch();mode='pause';draw();return VoidBabylon.diagnostics.frames>0&&VoidBabylon.diagnostics.exteriorReady;}));await flask.close();
  assert.deepEqual(errors,[]);console.log('PASS Babylon lazy boot, preloaded departure, reveal timing, unchanged flight controls, missile lock/impact, Rook interaction, boarding, Sol Earth/Mars, quality and scene disposal',JSON.stringify({sceneCounts}));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
