const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5000/void-runner.html');await page.waitForFunction(()=>window.VoidStartup?.started);await page.waitForFunction(()=>cockpitArt.complete&&cockpitArt.naturalWidth&&fleetTexture.complete);
 const result=await page.evaluate(()=>{state=C.fresh();state.quest='legal-run';launch();mode='pause';spawnEnemy();enemies[0].x=0;enemies[0].y=0;enemies[0].z=-65;draw();const rear=flight.arrows.some(a=>a.behind);flight.yaw=Math.PI;draw();const visible=flightPoint(enemies[0]).z>0;flight.yaw=0;mode='play';keys.add('KeyD');update(.2);keys.clear();mode='pause';return {rear,visible,turned:flight.yaw>0,graphic:cockpitArt.naturalWidth,sky:!!skyRenderer};});assert(result.rear&&result.visible&&result.turned&&result.graphic);console.log('Cockpit renderer:',result);
 const combat=await page.evaluate(()=>{flight.yaw=0;flight.pitch=0;flight.throttle=.3;enemies=[];spawned=0;current.enemies=1;spawnEnemy();const e=enemies[0];Object.assign(e,{x:0,y:0,z:16,armor:100,velocity:{x:0,y:0,z:-24},fire:99,passTime:3});for(let i=0;i<35;i++){mode='play';update(.04);}const passed=e.z<0;enemies=[{...e,x:0,y:0,z:-30,armor:1,maxArmor:1,dead:false,size:1,velocity:{x:0,y:0,z:0},fire:99}];flight.yaw=Math.PI;flight.pitch=0;flight.yawRate=flight.pitchRate=0;shot=0;keys.add('Space');for(let i=0;i<12&&enemies.length;i++){mode='play';update(.04);}keys.clear();mode='pause';return {passed,killed:enemies.length===0};});assert(combat.passed&&combat.killed);
 const missions=await page.evaluate(()=>{state.quest='open';state.contract='belt-1';launch();mode='play';missionObjects=[{x:0,y:0,z:3,kind:'salvage'}];cockpitMission(.01,{x:0,y:0,z:1});const salvage=objectiveCount===1;state.contract='lockdown-2';launch();spawnEnemy();spawnEnemy();const target=enemies[1],before=target.armor;hitEnemy(target,999);const protectedTarget=target.armor===before;hitEnemy(enemies[0],999);hitEnemy(target,999);mode='pause';return {salvage,protectedTarget,killed:target.dead};});assert(missions.salvage&&missions.protectedTarget&&missions.killed);
 await page.evaluate(()=>{state.contract='ghost';state.quest='open';launch();mode='pause';spawnEnemy();Object.assign(enemies[0],{x:12,y:-3,z:60});spawnEnemy();Object.assign(enemies[1],{x:-35,y:10,z:-60});flight.yaw=0;flight.pitch=0;flight.roll=0;draw();});
 const output=process.env.VOID_SCREENSHOT_DIR;if(output){fs.mkdirSync(output,{recursive:true});await page.screenshot({path:path.join(output,'cockpit-desktop.png')});}
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>draw());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(output)await page.screenshot({path:path.join(output,'cockpit-mobile.png')});
 await page.getByRole('button',{name:'Increase throttle'}).click();assert(await page.evaluate(()=>flight.throttle>.8));
 const fallback=await page.evaluate(()=>{const renderer=skyRenderer;skyRenderer=null;draw();skyRenderer=renderer;const before=flight.yaw;update(.2);return flight.yaw===before;});assert(fallback,'Pause freezes flight; canvas fallback renders');
 const touch=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});touch.on('pageerror',e=>errors.push(e.message));await touch.goto('http://127.0.0.1:5000/void-runner.html');await touch.waitForFunction(()=>window.VoidStartup?.started);await touch.waitForFunction(()=>typeof flight!=='undefined');
 const touchTurn=await touch.evaluate(()=>{state=C.fresh();state.quest='legal-run';launch();aim({clientX:innerWidth*.8,clientY:innerHeight*.44});update(.1);mode='pause';return flight.yaw>0;});assert(touchTurn);await touch.getByRole('button',{name:'Hold to fire weapons'}).waitFor({state:'visible'});
 assert.deepEqual(errors,[]);await browser.close();console.log('Cockpit checks passed: turning, rear arrows, enemy flyby, rear kill, salvage, relay protection, throttle, pause, renderer fallback and touch layout.');})().catch(e=>{console.error(e);process.exit(1);});
