const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{for(const port of [5000,5001]){const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));await page.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));await page.goto(`http://127.0.0.1:${port}/void-runner.html`);await page.waitForFunction(()=>window.VoidStartup?.started);
  await page.locator('[data-action=menu-new]').click();await page.locator('[data-action=story-intro]').click();await page.evaluate(()=>{for(let i=0;i<6;i++)advanceSpeech();});await page.locator('[data-action="story-choice:0"]').click();
  const relationship=await page.evaluate(()=>state.story.relationships.mara);await page.reload();await page.waitForFunction(()=>window.VoidStartup?.started);await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();assert.match(await page.locator('.sr-only').textContent(),/Keep her flying/);assert.equal(await page.evaluate(()=>state.story.relationships.mara),relationship);
  if(process.env.VOID_SCREENSHOT_DIR&&port===5000){const out=process.env.VOID_SCREENSHOT_DIR;fs.mkdirSync(out,{recursive:true});await page.evaluate(()=>{speech.shown=speech.lines[0].text.length;updateSpeech(0);});await page.screenshot({path:path.join(out,'dialogue.png')});await page.evaluate(()=>{advanceSpeech();flight.route=null;mode='pause';flight.yaw=flight.pitch=flight.roll=0;VoidCombatEffects.explode({x:0,y:0,z:60},'large');VoidCombatEffects.clouds[0].age=.5;draw();});await page.screenshot({path:path.join(out,'explosion.png')});}
  assert.deepEqual(errors,[]);console.log(`PASS ${port===5000?'static':'Flask mirrored'} entry point and dialogue checkpoint reload`);await page.close();}
  assert.equal(fs.readFileSync('void-runner.html','utf8'),fs.readFileSync('static/void-runner.html','utf8'));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
