require('node:fs').mkdirSync('work',{recursive:true});
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({hasTouch:true,viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));await page.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));await page.goto('http://127.0.0.1:5187/void-runner.html');await page.waitForFunction(()=>window.VoidStartup?.started);
 await page.evaluate(async()=>{state=C.fresh();state.quest='legal-run';await launch();flight.route=null;current.duration=999;current.enemies=0;enemies=[];spawned=resolved=0;});
 assert.equal(await page.evaluate(()=>VoidFactionEncounter.start([])),false);
 const result=await page.evaluate(()=>{VoidDevTools.authorized=true;VoidFactionEncounter.start([{id:'a',faction:'communion',role:'fighter',x:-25,y:0,z:90,hp:30},{id:'b',faction:'natural-order',role:'fighter',x:25,y:0,z:90,hp:30}]);const start=migrationSnapshot().ships.filter(a=>a.faction).length;for(let i=0;i<250;i++)update(.04);draw();return {start,actors:VoidFactionEncounter.actors.map(a=>({id:a.id,target:a.targetId,hp:a.hp,dead:!!a.dead})),renderer:VoidGraphics.renderer};});assert.equal(result.start,2);assert(result.actors.some(a=>a.dead));assert.equal(result.renderer,'babylon');assert(result.actors.every(a=>a.target===null||['a','b'].includes(a.target)));console.log('FACTION ENCOUNTER',result);
 const counts=[];for(let i=0;i<3;i++){await page.evaluate(async()=>{state.location='vesper';await enterWalking('vesper');});counts.push(await page.evaluate(()=>({meshes:VoidBabylon.scene.meshes.length,materials:VoidBabylon.scene.materials.length,textures:VoidBabylon.scene.textures.length})));}assert.deepEqual(counts[0],counts[2]);assert.equal(await page.evaluate(()=>VoidFactionEncounter.actors.length),0);
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{personalInventory();});assert(await page.locator('[data-action="personal-slot"]').isVisible());await page.locator('[data-action="progress-return"]').click();assert(await page.locator('[data-ground="inventory"]').isVisible());await page.screenshot({path:'work/prologue-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS opt-in visible faction combat, no player target, no population persistence, repeat Vesper resources and mobile controls.',counts);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
