const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
try{
 await p.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));await p.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));
 await p.goto('http://127.0.0.1:5187/void-runner.html');await p.waitForFunction(()=>window.VoidStartup?.started);await p.locator('[data-action="menu-new"]').click();await p.waitForFunction(()=>mode==='walking');
 assert.equal(await p.evaluate(()=>walkingLocation.kind),'workshop');assert.equal(await p.evaluate(()=>state.progression.personal.weapon),null);assert.equal(await p.evaluate(()=>VoidBabylon.scene.getTransformNodeByName('npc-elias')),null);
 await p.screenshot({path:'work/opening-workshop.png'});
 await p.keyboard.down('KeyW');await p.waitForTimeout(300);await p.keyboard.up('KeyW');await p.keyboard.down('KeyC');await p.waitForTimeout(300);assert(await p.evaluate(()=>walker.y<1.2));await p.keyboard.up('KeyC');await p.keyboard.press('Space');await p.waitForTimeout(130);assert(await p.evaluate(()=>walker.height>0));await p.waitForTimeout(800);
 async function interact(x,z,yaw){await p.evaluate(({x,z,yaw})=>{Object.assign(walker,{x,z,yaw,pitch:0,vx:0,vz:0});update(.016);interactWalking();},{x,z,yaw});}
 async function speech(){await p.evaluate(()=>{for(let i=0;i<12&&speech;i++){speech.shown=Infinity;advanceSpeech();}});}
 await interact(-6,-6,0);assert.equal(await p.evaluate(()=>mode),'dialogue');await speech();assert(await p.evaluate(()=>state.progression.opening.hologram));
 await interact(7,-7,0);await speech();await p.locator('[data-action="opening-choice:0"]').click();assert.equal(await p.evaluate(()=>state.progression.personal.weapon),'ward-pistol');
 const start=await p.evaluate(()=>VoidBabylon.opening.mara.position.z);await p.waitForTimeout(500);assert((await p.evaluate(()=>VoidBabylon.opening.mara.position.z))>start);
 await p.keyboard.press('Digit1');await p.evaluate(()=>{Object.assign(walker,{x:24,z:-8,yaw:Math.PI/2,pitch:0,vx:0,vz:0});groundAction('aim');});
 for(let id=0;id<4;id++){await p.evaluate(id=>{const pos=VoidOpening.cans[id].position,dx=pos[0]-walker.x,dz=pos[2]-walker.z;walker.yaw=Math.atan2(dx,dz);walker.pitch=Math.atan2(walker.y-pos[1],Math.hypot(dx,dz));},id);await p.mouse.click(720,450);await p.waitForTimeout(300);}
 console.log('CAN STATE',await p.evaluate(()=>state.progression.opening));assert.equal(await p.evaluate(()=>state.progression.opening.cans.length),4);assert(await p.evaluate(()=>VoidBabylon.opening.canNodes[0].node.position.x>39));
 await p.keyboard.press('KeyR');await p.waitForTimeout(1250);assert(await p.evaluate(()=>P.groundDone(state)));await p.screenshot({path:'work/opening-range.png'});
 await p.reload();await p.waitForFunction(()=>window.VoidStartup?.started);await p.locator('[data-action="menu-load"]').click();await p.locator('[data-action="menu-load-local"]').click();await p.waitForFunction(()=>mode==='walking');assert.equal(await p.evaluate(()=>state.progression.opening.cans.length),4);assert(await p.evaluate(()=>P.groundDone(state)));
 await interact(5,22,0);assert(await p.locator('[data-action="opening-start"]').count());await p.locator('[data-action="progress-inventory"]').click();await p.locator('[data-action="progress-return"]').click();await p.locator('[data-action="opening-start"]').click();await p.waitForFunction(()=>mode==='play');assert.equal(await p.evaluate(()=>state.quest),'arrival');assert.equal(await p.evaluate(()=>current.destination),'meridian');await p.evaluate(()=>draw());assert(await p.evaluate(()=>VoidBabylon.diagnostics.surfaceDeparture));assert(!await p.evaluate(()=>VoidBabylon.scene.getTransformNodeByName('station-vesper')));await p.screenshot({path:'work/opening-takeoff.png'});
 // Flight/arrival progression is accelerated deterministically; ground interactions use the real UI and ray hits.
 await p.evaluate(async()=>{await prepareDestination();mode='play';flight.route.phase='arrived';spawned=resolved=current.enemies;enemies=[];elapsed=current.duration;approachTime=10;arrive();});await p.waitForFunction(()=>mode==='walking'||mode==='dialogue');await speech();await p.waitForFunction(()=>mode==='walking');assert.equal(await p.evaluate(()=>state.location),'meridian');assert.equal(await p.evaluate(()=>walkingLocation.kind),'station');assert(await p.evaluate(()=>state.progression.equipment.owned.includes('cooling')));
 const counts=[];for(let i=0;i<3;i++){await p.evaluate(async()=>{state.location='vesper';VoidOpening.hooks.bench.src='assets/models/props/missing.glb';await enterWalking('vesper');});assert.equal(await p.evaluate(()=>mode),'walking');counts.push(await p.evaluate(()=>({meshes:VoidBabylon.scene.meshes.length,textures:VoidBabylon.scene.textures.length,lights:VoidBabylon.scene.lights.length})));}assert.deepEqual(counts[0],counts[2]);console.log('REPEAT COUNTS',counts);
 await p.route('**/slow-bench.glb',()=>{});await p.evaluate(async()=>{VoidOpening.hooks.bench.src='assets/models/props/slow-bench.glb';VoidPreparation.limits.optional=100;await enterWalking('vesper');VoidPreparation.limits.optional=3000;VoidOpening.hooks.bench.src=null;});assert.equal(await p.evaluate(()=>mode),'walking');
 const frame=await p.evaluate(()=>new Promise(resolve=>{const samples=[];let last=performance.now();function frame(now){samples.push(now-last);last=now;if(samples.length<120)requestAnimationFrame(frame);else{samples.sort((a,b)=>a-b);resolve({medianMs:samples[60],p95Ms:samples[114],meshes:VoidBabylon.scene.meshes.length});}}requestAnimationFrame(frame);}));console.log('HEADLESS FRAME SAMPLE',frame);
 await p.setViewportSize({width:1920,height:1080});await p.screenshot({path:'work/opening-desktop.png'});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'work/opening-narrow.png'});assert(await p.locator('#tutorial-prompt').evaluate(e=>e.getBoundingClientRect().height<120));
 const touch=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});touch.on('pageerror',e=>errors.push(e.message));await touch.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));await touch.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));await touch.goto('http://127.0.0.1:5187/void-runner.html');await touch.waitForFunction(()=>window.VoidStartup?.started);await touch.locator('[data-action="menu-new"]').click();await touch.waitForFunction(()=>mode==='walking');await touch.locator('[data-ground="crouch"]').tap();await touch.waitForTimeout(250);assert(await touch.evaluate(()=>walker.y<1.2));await touch.screenshot({path:'work/opening-touch.png'});await touch.close();
 assert.deepEqual(errors,[]);console.log('PASS New Campaign, movement/crouch/jump, recording, gift, Mara movement, ray-hit cans, reload, save refresh, boarding/inventory/departure, Meridian reward and station, missing GLB, scene disposal, narrow viewport.');
}finally{console.log('ERRORS',errors);await b.close();}})().catch(e=>{console.error(e);process.exit(1);});
