const test=require('node:test'),assert=require('node:assert/strict'),P=require('../void-runner/progression.js'),C=require('../void-runner/campaign.js'),U=require('../void-runner/universe.js'),F=require('../void-runner/factions.js');
function fresh(){return C.fresh();}
test('new prologue never opens on voucher; actions persist and early attachment counts',()=>{let s=fresh();s.progression.opening={version:2,hologram:true,pistol:true,cans:[0,1,2,3]};s.missileOfferSeen=true;s.missileUnlocked=true;U.unlock(s);assert.equal(s.universe.freeTravel,false);s.progression.personal.attachments=['red-dot'];s.progression.personal.optic='red-dot';P.sync(s);assert(s.progression.flags.sightEquipped);for(const f of P.flags.filter(f=>f!=='missileFired'))P.mark(s,f);assert(!s.progression.completed);P.mark(s,'missileFired');U.unlock(s);assert(s.universe.freeTravel);let r=C.restore(JSON.stringify(s));assert(r.progression.completed);assert.equal(P.next(r),null);});
test('purchase does not install; equipment compatibility, removal, safe checkpoint and death',()=>{const s=fresh();s.credits=500;assert(P.buy(s,'capacitor'));assert.equal(s.credits,350);assert.equal(P.systems(s).capacity,72);assert(!P.install(s,'weapon','capacitor'));assert(P.install(s,'power','capacitor'));assert.equal(P.systems(s).capacity,96);P.checkpoint(s,'kepler');s.location='earth';s.travel={phase:'warp'};P.respawn(s);assert.equal(s.location,'kepler');assert.equal(s.credits,350);assert.equal(s.travel,null);assert(s.progression.equipment.owned.includes('capacitor'));assert(P.install(s,'power',null));assert.equal(P.systems(s).capacity,72);});
test('energy and heat are independent, capped, and cooled lockout recovers',()=>{const s=fresh(),b={energy:72,heat:0,overheated:false};for(let i=0;i<8;i++){b.energy=72;assert(P.consume(b,s));}assert(b.overheated);assert(!P.consume(b,s));for(let i=0;i<5;i++)P.powerStep(b,s,1);assert(!b.overheated);assert.equal(b.energy,72);b.energy=0;assert(!P.consume(b,s));});
test('existing open saves retain access without replay and in-progress saves keep Rook state',()=>{const s=fresh();delete s.progression;s.quest='open';s.missileOfferSeen=true;s.combatRuns=2;let r=C.restore(JSON.stringify(s));assert(r.progression.completed);assert.equal(r.quest,'open');s.quest='legal-run';s.missileOfferSeen=false;s.universe.freeTravel=false;r=C.restore(JSON.stringify(s));assert(P.groundDone(r));assert(!r.progression.completed);assert.equal(r.quest,'legal-run');});
test('factions choose NPC threats without player bias; civilians flee; targets can change',()=>{const a={id:'a',faction:'communion',role:'fighter',x:0,z:0,hp:50},b={id:'b',faction:'natural-order',role:'fighter',x:0,z:40,hp:50},p={id:'player',faction:'player',player:true,x:0,z:2,hp:100};assert.equal(F.select(a,[a,b,p]),b);for(let i=0;i<200;i++)F.step([a,b,p],.1);assert(a.dead||b.dead);assert.equal(p.hp,100);const ally={id:'c',faction:'communion',x:0,z:1};assert.notEqual(F.attitude(a,ally),'hostile');const civ={id:'civil',faction:'civilian',role:'civilian',x:0,z:0,hp:100},pirate={id:'pirate',faction:'pirate',x:0,z:20,hp:100};F.step([civ,pirate],.1);assert.equal(civ.behavior,'flee');assert(civ.z<0);});
test('cargo/data capacity and relay outages never disable local services',()=>{const s=fresh();assert.equal(P.systems(s).cargo,1);assert(F.recover(s,{id:'parts',units:1},1,null));assert(!F.recover(s,{id:'parts',units:1},1,null));s.progression.data.push('encrypted');assert.equal(F.cargoUsed(s),1);assert.equal(F.salvage([{id:'parts',units:1}],()=>.7).length,0);s.progression.relays.sol='offline';assert(F.relay(s,'sol').localServices);assert(!F.relay(s,'sol').remoteCurrent);});
test('forged premium hull cannot grant power or cargo without account verification',()=>{const s=fresh();s.activeShip='ship3';s.ownedShips.push('ship3');assert.equal(P.systems(s).capacity,72);assert.equal(P.systems(s).cargo,1);});
