const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));await page.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));
 await page.goto('http://127.0.0.1:5187/void-runner.html');await page.waitForFunction(()=>window.VoidStartup?.started);await page.locator('[data-action="menu-new"]').click();await page.waitForFunction(()=>mode==='walking');
 assert.equal(await page.evaluate(()=>walkingLocation.kind),'workshop');assert.equal(await page.evaluate(()=>state.progression.personal.weapon),null);assert.equal(await page.evaluate(()=>VoidBabylon.scene.getTransformNodeByName('npc-elias')),null);
 await page.screenshot({path:'work/opening-workshop.png'});
 await page.keyboard.down('KeyW');await page.waitForTimeout(300);await page.keyboard.up('KeyW');await page.keyboard.down('KeyC');await page.waitForTimeout(300);assert(await page.evaluate(()=>walker.y<1.2));await page.keyboard.up('KeyC');await page.keyboard.press('Space');await page.waitForTimeout(130);assert(await page.evaluate(()=>walker.height>0));await page.waitForTimeout(800);
 async function interact(x,z,yaw){await page.evaluate(({x,z,yaw})=>{Object.assign(walker,{x,z,yaw,pitch:0,vx:0,vz:0});update(.016);interactWalking();},{x,z,yaw});}
 async function speech(){await page.evaluate(()=>{for(let i=0;i<12&&speech;i++){speech.shown=Infinity;advanceSpeech();}});}
 await interact(-6,-6,0);assert.equal(await page.evaluate(()=>mode),'dialogue');await speech();assert(await page.evaluate(()=>state.progression.opening.hologram));
 await interact(7,-7,0);await speech();await page.locator('[data-action="opening-choice:0"]').click();assert.equal(await page.evaluate(()=>state.progression.personal.weapon),'ward-pistol');
 const start=await page.evaluate(()=>VoidBabylon.opening.mara.position.z);await page.waitForTimeout(500);assert((await page.evaluate(()=>VoidBabylon.opening.mara.position.z))>start);
 await page.keyboard.press('Digit1');await page.evaluate(()=>{Object.assign(walker,{x:24,z:-8,yaw:Math.PI/2,pitch:0,vx:0,vz:0});groundAction('aim');});
 for(let id=0;id<4;id++){await page.evaluate(id=>{const pos=VoidOpening.cans[id].position,dx=pos[0]-walker.x,dz=pos[2]-walker.z;walker.yaw=Math.atan2(dx,dz);walker.pitch=Math.atan2(walker.y-pos[1],Math.hypot(dx,dz));},id);await page.mouse.click(720,450);await page.waitForTimeout(300);}
 console.log('CAN STATE',await page.evaluate(()=>state.progression.opening));assert.equal(await page.evaluate(()=>state.progression.opening.cans.length),4);assert(await page.evaluate(()=>VoidBabylon.opening.canNodes[0].node.position.x>39));
 await page.keyboard.press('KeyR');await page.waitForTimeout(1250);assert(await page.evaluate(()=>P.groundDone(state)));await page.screenshot({path:'work/opening-range.png'});
 await page.reload();await page.waitForFunction(()=>window.VoidStartup?.started);await page.locator('[data-action="menu-load"]').click();await page.locator('[data-action="menu-load-local"]').click();await page.waitForFunction(()=>mode==='walking');assert.equal(await page.evaluate(()=>state.progression.opening.cans.length),4);assert(await page.evaluate(()=>P.groundDone(state)));
 await interact(5,22,0);assert(await page.locator('[data-action="opening-start"]').count());await page.locator('[data-action="progress-inventory"]').click();await page.locator('[data-action="progress-return"]').click();await page.locator('[data-action="opening-start"]').click();await page.waitForFunction(()=>mode==='play');assert.equal(await page.evaluate(()=>state.quest),'arrival');assert.equal(await page.evaluate(()=>current.destination),'meridian');await page.evaluate(()=>draw());assert(await page.evaluate(()=>VoidBabylon.diagnostics.surfaceDeparture));assert(!await page.evaluate(()=>VoidBabylon.scene.getTransformNodeByName('station-vesper')));await page.screenshot({path:'work/opening-takeoff.png'});
await page.evaluate(()=>{flight.route.phase='align';for(const action of ['throttleUp','yawRight','rollRight'])VoidInput.held.add(VoidInput.bindings[action]);for(let i=0;i<10;i++)update(.04);VoidInput.held.clear();flight.route.phase='warp';update(.01);});
async function finish(){await page.evaluate(async()=>{await prepareDestination();mode='play';flight.route.phase='arrived';spawned=resolved=current.enemies;enemies=[];elapsed=current.duration;approachTime=10;arrive();});await page.waitForFunction(()=>mode==='walking'||mode==='dialogue');await page.evaluate(()=>{while(speech){speech.shown=Infinity;advanceSpeech();}});await page.waitForFunction(()=>mode==='walking');}
await finish();await page.evaluate(()=>shipInventory());await page.locator('[data-action="progress-hangar"]').click();await page.locator('[data-action="module-slot:cooling"]').click();await page.locator('[data-action="module-install:cooling:cooling"]').click();await page.locator('[data-action="progress-return"]').click();await page.evaluate(()=>equipmentShop());await page.locator('[data-action="module-buy:capacitor"]').click();assert.equal(await page.evaluate(()=>P.systems(state).capacity),72);await page.locator('[data-action="progress-return"]').click();await page.evaluate(()=>maintenance('power'));await page.locator('[data-action="module-install:power:capacitor"]').click();assert.equal(await page.evaluate(()=>P.systems(state).capacity),96);await page.screenshot({path:'work/prologue-hangar.png'});await page.locator('[data-action="progress-return"]').click();
await page.evaluate(()=>{C.accept(state);save();});await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');await page.evaluate(()=>{flight.route.phase='encounter';spawnEnemy();hitEnemy(enemies[0],999);});await finish();await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');await finish();await page.evaluate(()=>{C.accept(state);save();});await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');await finish();
assert(await page.evaluate(()=>state.missileOfferSeen));assert(!await page.evaluate(()=>state.universe.freeTravel));await page.evaluate(()=>equipmentShop());await page.locator('[data-action="module-launcher"]').click();await page.locator('[data-action="progress-return"]').click();await page.evaluate(()=>maintenance('missile'));await page.locator('[data-action="module-install:missile:launcher"]').click();await page.locator('[data-action="progress-return"]').click();await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');
await page.evaluate(()=>{flight.route.phase='encounter';enemies=[];spawnEnemy();Object.assign(enemies[0],{x:0,y:0,z:55,size:3});flight.yaw=flight.pitch=flight.roll=0;selectCombatTarget('nearest');selectCombatTarget('lock');for(let i=0;i<200;i++)VoidTargeting.step(missileLock,lockCandidates(),flightPoint,W,H,.04,missileBalance(),true);fireMissile();});
console.log('FLIGHT',await page.evaluate(()=>({flags:state.progression.flags,next:P.next(state),completed:state.progression.completed})));assert(await page.evaluate(()=>state.progression.completed));assert(await page.evaluate(()=>state.universe.freeTravel));
await page.evaluate(async()=>{await safeRespawn();});await page.waitForFunction(()=>mode==='walking');assert.equal(await page.evaluate(()=>state.location),'undertow');await page.reload();await page.waitForFunction(()=>window.VoidStartup?.started);await page.locator('[data-action="menu-load"]').click();await page.locator('[data-action="menu-load-local"]').click();await page.waitForFunction(()=>mode==='walking');assert(await page.evaluate(()=>state.progression.completed));assert.equal(await page.evaluate(()=>P.systems(state).capacity),96);
for(const id of ['sol-belt','earth']){await page.evaluate(async id=>{if(!C.chooseDestination(state,id))throw Error('Route unavailable '+id);await leaveWalking();},id);await page.waitForFunction(()=>mode==='play');await finish();}await page.waitForFunction(()=>mode==='walking');assert.equal(await page.evaluate(()=>walker.z),-27);await page.evaluate(()=>{walker.x=0;walker.z=28;walker.yaw=0;update(.03);interactWalking();});assert(await page.evaluate(()=>state.story.flags.districtDoor));await page.evaluate(()=>{walker.x=0;walker.z=36;walker.yaw=0;update(.03);interactWalking();});assert(await page.evaluate(()=>state.story.flags.metAdmin&&state.story.flags.metIris));assert.deepEqual(errors,[]);console.log('PASS restored opening, original dialogue choice, can practice, module purchase/install, missile gate, safe recovery/reload, physical District entry.');
}finally{console.log('ERRORS',errors);await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
