require('node:fs').mkdirSync('work',{recursive:true});
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));await page.route('**/firebase-auth.js',r=>r.fulfill({status:503,body:'offline'}));await page.goto('http://127.0.0.1:5187/void-runner.html');await page.waitForFunction(()=>window.VoidStartup?.started);await page.locator('[data-action="menu-new"]').click();await page.waitForFunction(()=>mode==='walking');
await page.keyboard.down('KeyW');await page.waitForTimeout(200);await page.keyboard.down('Shift');await page.waitForTimeout(200);await page.keyboard.up('Shift');await page.keyboard.up('KeyW');await page.keyboard.press('Space');await page.evaluate(()=>{walker.yaw=.3;update(.03);});
await page.evaluate(()=>{walker.x=0;walker.z=-14;walker.yaw=0;update(.03);interactWalking();while(speech){speech.shown=Infinity;advanceSpeech();}});
await page.evaluate(()=>{walker.x=8;walker.z=-19;walker.yaw=0;update(.03);interactWalking();});
await page.keyboard.press('Digit1');await page.evaluate(()=>{walker.x=8;walker.z=-10;walker.y=1.7;walker.yaw=0;walker.pitch=0;groundState.jump=0;groundAction('aim');});
for(let i=0;i<3;i++){await page.locator('[data-ground="fire"]').click();await page.waitForTimeout(300);}await page.locator('[data-ground="reload"]').click();await page.waitForTimeout(1200);await page.locator('[data-ground="draw"]').click();
await page.locator('[data-ground="inventory"]').click();await page.locator('[data-action="progress-return"]').click();await page.evaluate(()=>{walker.x=-10;walker.z=24;walker.yaw=0;update(.03);interactWalking();});await page.locator('[data-action="personal-buy"]').click();await page.locator('[data-action="progress-return"]').click();await page.locator('[data-ground="inventory"]').click();await page.locator('[data-action="personal-slot"]').click();await page.locator('[data-action="personal-optic"]').click();await page.locator('[data-action="personal-equip"]').click();await page.locator('[data-action="progress-return"]').click();await page.locator('[data-ground="draw"]').click();await page.evaluate(()=>{groundState.aim=false;groundAction('aim');});
console.log('GROUND',await page.evaluate(()=>({flags:state.progression.flags,next:P.next(state)})));assert(await page.evaluate(()=>P.groundDone(state)));await page.screenshot({path:'work/prologue-sight.png'});
await page.evaluate(()=>{walker.x=0;walker.z=-14;walker.yaw=0;update(.03);interactWalking();});
for(let i=0;i<30;i++){const info=await page.evaluate(()=>({mode,speech:!!speech,choice:!!document.querySelector('[data-action="story-choice:0"]')}));if(info.mode==='play')break;if(info.choice)await page.locator('[data-action="story-choice:0"]').click();else if(info.speech)await page.evaluate(()=>{speech.shown=Infinity;advanceSpeech();});else await page.waitForTimeout(100);}
await page.waitForFunction(()=>mode==='walking'&&state.quest==='arrival');await page.evaluate(()=>{walker.x=-2;walker.z=-16;walker.yaw=0;update(.03);interactWalking();});await page.waitForFunction(()=>mode==='play');assert.equal(await page.evaluate(()=>state.quest),'arrival');assert(!await page.evaluate(()=>state.universe.freeTravel));
await page.evaluate(()=>{flight.route.phase='align';for(const action of ['throttleUp','yawRight','rollRight'])VoidInput.held.add(VoidInput.bindings[action]);for(let i=0;i<10;i++)update(.04);VoidInput.held.clear();flight.route.phase='warp';update(.01);});
async function finish(){await page.evaluate(async()=>{await prepareDestination();mode='play';flight.route.phase='arrived';spawned=resolved=current.enemies;enemies=[];elapsed=current.duration;approachTime=10;arrive();});await page.waitForFunction(()=>mode==='walking'||mode==='dialogue');await page.evaluate(()=>{while(speech){speech.shown=Infinity;advanceSpeech();}});await page.waitForFunction(()=>mode==='walking');}
await finish();await page.evaluate(()=>maintenance());await page.locator('[data-action="progress-hangar"]').click();await page.locator('[data-action="module-slot:cooling"]').click();await page.locator('[data-action="module-install:cooling:cooling"]').click();await page.locator('[data-action="progress-return"]').click();await page.evaluate(()=>equipmentShop());await page.locator('[data-action="module-buy:capacitor"]').click();assert.equal(await page.evaluate(()=>P.systems(state).capacity),72);await page.locator('[data-action="progress-return"]').click();await page.evaluate(()=>maintenance('power'));await page.locator('[data-action="module-install:power:capacitor"]').click();assert.equal(await page.evaluate(()=>P.systems(state).capacity),96);await page.screenshot({path:'work/prologue-hangar.png'});await page.locator('[data-action="progress-return"]').click();
await page.evaluate(()=>{C.accept(state);save();});await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');await page.evaluate(()=>{flight.route.phase='encounter';spawnEnemy();hitEnemy(enemies[0],999);});await finish();await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');await finish();await page.evaluate(()=>{C.accept(state);save();});await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');await finish();
assert(await page.evaluate(()=>state.missileOfferSeen));assert(!await page.evaluate(()=>state.universe.freeTravel));await page.evaluate(()=>equipmentShop());await page.locator('[data-action="module-launcher"]').click();await page.locator('[data-action="progress-return"]').click();await page.evaluate(()=>maintenance('missile'));await page.locator('[data-action="module-install:missile:launcher"]').click();await page.locator('[data-action="progress-return"]').click();await page.evaluate(async()=>leaveWalking());await page.waitForFunction(()=>mode==='play');
await page.evaluate(()=>{flight.route.phase='encounter';enemies=[];spawnEnemy();Object.assign(enemies[0],{x:0,y:0,z:55,size:3});flight.yaw=flight.pitch=flight.roll=0;selectCombatTarget('nearest');selectCombatTarget('lock');for(let i=0;i<200;i++)VoidTargeting.step(missileLock,lockCandidates(),flightPoint,W,H,.04,missileBalance(),true);fireMissile();});
console.log('FLIGHT',await page.evaluate(()=>({flags:state.progression.flags,next:P.next(state),completed:state.progression.completed})));assert(await page.evaluate(()=>state.progression.completed));assert(await page.evaluate(()=>state.universe.freeTravel));
await page.evaluate(async()=>{await safeRespawn();});await page.waitForFunction(()=>mode==='walking');assert.equal(await page.evaluate(()=>state.location),'undertow');await page.reload();await page.waitForFunction(()=>window.VoidStartup?.started);await page.locator('[data-action="menu-load"]').click();await page.locator('[data-action="menu-load-local"]').click();await page.waitForFunction(()=>mode==='walking');assert(await page.evaluate(()=>state.progression.completed));assert.equal(await page.evaluate(()=>P.systems(state).capacity),96);
for(const id of ['sol-belt','earth']){await page.evaluate(async id=>{if(!C.chooseDestination(state,id))throw Error('Route unavailable '+id);await leaveWalking();},id);await page.waitForFunction(()=>mode==='play');await finish();}await page.waitForFunction(()=>mode==='walking');assert.equal(await page.evaluate(()=>walker.z),-27);await page.evaluate(()=>{walker.x=0;walker.z=28;walker.yaw=0;update(.03);interactWalking();});assert(await page.evaluate(()=>state.story.flags.districtDoor));await page.evaluate(()=>{walker.x=0;walker.z=36;walker.yaw=0;update(.03);interactWalking();});assert(await page.evaluate(()=>state.story.flags.metAdmin&&state.story.flags.metIris));assert.deepEqual(errors,[]);console.log('PASS fresh ground actions, attachment UI, original story, module purchase/install, missile gate, safe recovery/reload, physical District entry.');
}finally{console.log('ERRORS',errors);await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
