const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.route('**/api/void-runner/**',r=>r.fulfill({status:503,body:'offline'}));await page.route('**/firebase-auth.js',r=>r.abort());await page.goto('http://127.0.0.1:5189/void-runner.html');await page.waitForFunction(()=>VoidStartup.started);
 await page.evaluate(async()=>{state=C.fresh();state.quest='open';state.location='meridian';state.universe.freeTravel=true;state.universe.trackingInitialized=true;state.progression.opening={version:2,hologram:true,pistol:true,cans:[0,1,2,3]};for(const id of VoidProgression.ground)VoidProgression.mark(state,id);await enterWalking('hangar');});
 assert.equal(await page.evaluate(()=>mode),'walking');
 const door=await page.evaluate(()=>{walker.x=0;walker.z=2;walker.yaw=0;update(.01);const id=walkTarget?.id;interactWalking();draw();return {id,open:walkingLocation.solids.find(s=>s.id==='crew-pressure-door').open,mesh:VoidBabylon.scene.getMeshByName('crew-pressure-door').position.y};});assert.equal(door.id,'crew-pressure-door');assert(door.open);assert(door.mesh>4);
 await page.evaluate(()=>{walker.x=0;walker.z=19;walker.yaw=.35;walker.pitch=0;draw();});await page.screenshot({path:'../../outputs/recovery-meridian-concourse.png'});
 await page.evaluate(()=>{walker.x=4;walker.z=35;walker.yaw=1;walker.pitch=0;draw();});await page.screenshot({path:'../../outputs/recovery-meridian-lounge.png'});
 await page.evaluate(()=>{walker.x=5;walker.z=52;walker.yaw=Math.PI/2;update(.01);interactWalking();draw();});assert(await page.evaluate(()=>walkingLocation.solids.find(s=>s.id==='quarters-door').open));
 await page.evaluate(()=>{walker.x=10;walker.z=52;walker.yaw=.8;draw();});await page.screenshot({path:'../../outputs/recovery-meridian-quarters.png'});
 const meshes=await page.evaluate(()=>VoidBabylon.scene.meshes.length);await page.waitForTimeout(1500);assert.equal(await page.evaluate(()=>VoidBabylon.scene.meshes.length),meshes);
 await page.evaluate(()=>renderMainMenu());await page.locator('[data-action="menu-skirmish"]').click();await page.locator('[data-action="skirmish-type:flight"]').click();for(let i=0;i<5;i++)await page.locator('[data-action="flight-next"]').click();await page.locator('[data-action="flight-start"]').click();await page.waitForFunction(()=>VoidFlightSkirmish.active?.status==='active');
 const campaign=await page.evaluate(()=>JSON.stringify(VoidFlightSkirmish.active.original));await page.locator('#sensor-toggle').click();assert.equal(await page.evaluate(()=>VoidFlightSensors.state.radar),false);assert.equal(await page.evaluate(()=>lockCandidates().length),0);await page.evaluate(()=>{VoidFlightSensors.state.weapons=0;VoidSensors.step(VoidFlightSensors.state,0,{throttle:0});});const cold=await page.evaluate(()=>VoidFlightSensors.state.signature.total);await page.evaluate(()=>VoidSensors.step(VoidFlightSensors.state,.1,{throttle:1,firing:true}));assert(await page.evaluate(()=>VoidFlightSensors.state.signature.total)>cold);assert.equal(await page.evaluate(()=>JSON.stringify(VoidFlightSkirmish.active.original)),campaign);
 await page.screenshot({path:'../../outputs/recovery-go-dark.png'});await page.evaluate(async()=>{await VoidFlightSkirmish.end();renderMainMenu();});
 assert.deepEqual(errors,[]);console.log('Recovery browser: Meridian doors/rooms/screenshots, stable meshes, Flight setup, Go Dark, and Campaign isolation passed.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
