/* Station menus reuse the campaign inventory and account-verified equipment list. */
function shipDetails(ship){return row('Hull / shields',ship.hull+' / '+ship.shield)+row('Shield recharge',ship.recharge+' / sec')+row('Top speed / acceleration',ship.flight.maxSpeed+' / '+ship.flight.acceleration)+row('Yaw / pitch',ship.flight.yawRate+' / '+ship.flight.pitchRate)+row('Laser damage',ship.laser+' × base')+row('Missile rack',ship.missile.capacity+' / launcher required');}
function hangar(){
 view='hangar';const ship=VoidShips.get(state),gear={...VoidShips.equipment,...VoidContent.creditGear,...VoidContent.gear};
 menuPage(C.stations[state.location].name.toUpperCase()+' / HANGAR','Your ships. <em>Your loadout.</em>',
  '<p>Switch ships here. Each hull keeps its loadout. Swap owned weapons, shields and utilities between ships.</p><div class="hangar-grid">'+Object.values(VoidShips.ships).map(s=>`<article class="card" style="--ship-color:${s.color}"><span class="tag">${state.activeShip===s.id?'ACTIVE SHIP':VoidShips.owns(state,s.id)?'OWNED':'NOT OWNED'}</span><h2>${s.name}</h2>${shipDetails(s)}${button(state.activeShip===s.id?'ACTIVE':VoidShips.owns(state,s.id)?'SELECT SHIP':'BUY AT STATION SHOP','ship-select:'+s.id,false,!VoidShips.owns(state,s.id)||state.activeShip===s.id)}</article>`).join('')+'</div><h2>'+ship.name+' / EQUIPMENT</h2><div class="hangar-grid">'+['weapon','shield','utility','missile'].map(slot=>'<section class="card"><h3>'+slot.toUpperCase()+'</h3>'+Object.entries(gear).filter(([,g])=>g.slot===slot).map(([id,g])=>{const owned=C.ownsEquipment(state,id,ownedGear),active=state.loadout[slot]===id;return `<div class="hangar-item"><span>${g.name}<small>${owned?'OWNED':VoidContent.gear[id]?'ACCOUNT ITEM':'LOCKED'}</small></span>${button(active?'UNEQUIP':owned?'EQUIP':'LOCKED','hangar-equip:'+id,true,!owned)}</div>`;}).join('')+'</section>').join('')+'</div>'+button('STATION SHOP','shop'));
}
const hangarShop=shop;
shop=function(){
 hangarShop();if(view!=='shop')return;
 const container=screen.querySelector('.shop-layout');if(!container)return;
 container.insertAdjacentHTML('beforeend','<section aria-label="Ship store"><h2>SHIP STORE</h2><p>Peregrine uses campaign credits. Spectre requires a verified account purchase. Select owned hulls in the Hangar.</p><div class="hangar-grid">'+Object.values(VoidShips.ships).map(s=>`<article class="card"><h3>${s.name}</h3>${shipDetails(s)}${s.premium?'<span class="tag">PREMIUM SHIP</span>'+row('Price','$1.00 USD')+button(VoidShips.owns(state,s.id)?'OWNED · SELECT IN HANGAR':'PURCHASE / $1.00 USD',VoidShips.owns(state,s.id)?'hangar':'purchase:spectre',false,!!window.VoidAccount?.busy):row('Price',s.price+' CR')+button(VoidShips.owns(state,s.id)?'OWNED':'BUY SHIP / '+s.price+' CR','ship-buy:'+s.id,false,VoidShips.owns(state,s.id)||state.credits<s.price)}</article>`).join('')+'</div></section><h2>STANDARD OUTFITTING</h2><div class="hangar-grid">'+Object.entries(C.upgrades).map(([id,g])=>`<article class="card"><h3>${g.name}</h3><p>${g.description}</p>${button(state.upgrades[id]>=3?'MAXIMUM TIER':'UPGRADE / '+g.prices[state.upgrades[id]]+' CR','buy:'+id,false,state.upgrades[id]>=3||state.credits<g.prices[state.upgrades[id]])}</article>`).join('')+Object.entries(VoidContent.creditGear).map(([id,g])=>{const owned=state.creditGear.includes(id),locked=id==='launcher'&&!state.missileUnlocked;return `<article class="card"><h3>${g.name}</h3><p>${g.description}</p>${button(owned?'OWNED':locked?'COMPLETE TWO COMBAT RUNS':id==='launcher'?'INSTALL / ROOK’S VOUCHER':'BUY / '+g.price+' CR','credit-gear:'+id,false,owned||locked||state.credits<g.price)}</article>`;}).join('')+'</div>'+button('OPEN HANGAR','hangar'));
};
const rookMissileLine={who:'rook',text:'Two hot runs and you’re still breathing. I’ve got something for the next one. Head to the station shop. Tell them Rook sent you. They’ll fit a missile launcher — installation’s on me. I know a guy in SOL with more work. Admin. Runs The Darknet District in Sacramento with his partner Iris. I’ve marked the Sol Belt Anchorage. Press F1 for your Mission Log; pick what you want to track. Complete your missile qualification before choosing independent routes. Acquire the launcher here, fit it in the hangar, and demonstrate target selection, lock and firing on your next run.'};
function missileOffer(){if(!state.missileUnlocked||state.missileOfferSeen)return false;state.missileOfferSeen=true;VoidUniverse.unlock(state);save();talk('dock',[rookMissileLine],()=>shop(),'OPEN STATION SHOP →','A message from Rook');return true;}
const hangarDock=dock;
dock=function(tab='dock'){departureImages[state.location]?.load();if(tab==='dock'&&missileOffer())return;hangarDock(tab);if(tab==='dock'&&view==='dock')screen.querySelector('.actions')?.insertAdjacentHTML('beforeend',button('HANGAR','hangar',true)+(state.quest==='open'?button('NAVIGATION','navigation',true):''));};
const hangarArrive=arrive;
arrive=function(){const before=state.combatRuns;hangarArrive();if(state.combatRuns>before&&state.missileUnlocked&&!state.missileOfferSeen&&speech){speech.lines.push(rookMissileLine);state.missileOfferSeen=true;VoidUniverse.unlock(state);save();}};
function navigation(){view='navigation';menuPage('FLIGHT PLANNING','Choose a <em>destination.</em>','<p>Launch, turn toward the destination marker, and hold alignment to engage warp. Hostiles can pull you out en route.</p><div class="hangar-grid">'+Object.entries(C.stations).map(([id,s])=>`<article class="card"><h3>${s.name}</h3>${button(id===state.location?'CURRENT LOCATION':'PLOT ROUTE','destination:'+id,false,id===state.location||!!state.contract)}</article>`).join('')+'</div>');}
function hangarAction(e){const a=e.target.closest('button')?.dataset.action;if(['play','pause'].includes(mode))return;
 if(a==='hangar')hangar();else if(a==='navigation')navigation();
 else if(a?.startsWith('ship-buy:')){if(C.buyShip(state,a.slice(9))){save();hud();shop();announce('Ship added to your Hangar. Your active ship is unchanged.');}}
 else if(a?.startsWith('ship-select:')){if(C.switchShip(state,a.slice(12))){save();hud();hangar();announce(VoidShips.get(state).name+' selected.');}}
 else if(a?.startsWith('hangar-equip:')){if(C.equip(state,a.slice(13),ownedGear)){save();hud();hangar();}}
 else if(a?.startsWith('destination:')){if(C.chooseDestination(state,a.slice(12))){save();launch();}}
}
screen.addEventListener('click',hangarAction);
