/* Bounded Babylon workshop scene. Asset hooks replace models, not gameplay anchors. */
(function(root){
 function build({scene,parent,quality,shadowLight,characterModel,shipModel,state,camera}){
  const B=BABYLON,low=quality==='low',owned=[],textures=[],staticMeshes=[],dynamic=[],canNodes=[],v=(x,y,z)=>new B.Vector3(x,y,z);
  let seed=719;const rand=()=>((seed=seed*16807%2147483647)-1)/2147483646;
  const mats={};
  function texture(name,color){const t=new B.DynamicTexture('ward-'+name,{width:256,height:256},scene,false);textures.push(t);const g=t.getContext();g.fillStyle=color;g.fillRect(0,0,256,256);for(let i=0;i<1300;i++){const a=rand()*.10;g.fillStyle=rand()>.5?'rgba(235,222,196,'+a+')':'rgba(29,25,22,'+a+')';g.fillRect(rand()*256,rand()*256,1+rand()*9,1+rand()*2);}for(let i=0;i<20;i++){g.strokeStyle='rgba(35,28,22,.10)';g.beginPath();g.moveTo(rand()*256,rand()*256);g.lineTo(rand()*256,rand()*256);g.stroke();}t.update();t.anisotropicFilteringLevel=low?2:4;return t;}
  function mat(name,color,rough=.8,metal=.1,glow){if(mats[name])return mats[name];const m=new B.PBRMaterial('ward-'+name,scene);owned.push(m);m.albedoColor=B.Color3.FromHexString(color);m.roughness=rough;m.metallic=metal;m.environmentIntensity=.6;if(glow)m.emissiveColor=B.Color3.FromHexString(glow);mats[name]=m;return m;}
  const sand=mat('sand','#ad8662'),paint=mat('paint','#887b68',.86,.25),steel=mat('steel','#464b4a',.58,.45),rust=mat('faded-orange','#b4773a',.77,.25),dark=mat('rubber','#222b2e',.9),floorMat=mat('concrete','#9d9483'),blue=mat('monitor','#163443',.5,.2,'#3289a8'),warm=mat('warm','#efd59b',.5,.1,'#ffc373'),cloth=mat('cloth','#656b56');
  paint.albedoTexture=texture('paint','#b5a793');paint.albedoColor.set(1,1,1);floorMat.albedoTexture=texture('floor','#aaa293');floorMat.albedoTexture.uScale=floorMat.albedoTexture.vScale=8;floorMat.albedoColor.set(1,1,1);sand.albedoTexture=texture('soil','#c2a280');sand.albedoColor.set(1,1,1);sand.albedoTexture.uScale=sand.albedoTexture.vScale=50;
  // A small tiled, generated surface keeps weathering local and download-free.
  const wear=new B.DynamicTexture('workshop-floor-wear',{width:1024,height:1024},scene,false);textures.push(wear);const wg=wear.getContext();wg.fillStyle='#8f8777';wg.fillRect(0,0,1024,1024);
  for(let i=0;i<16000;i++){wg.fillStyle=rand()>.5?'rgba(40,32,23,.14)':'rgba(235,221,195,.12)';wg.fillRect(rand()*1024,rand()*1024,1+rand()*3,1+rand()*2);}
  for(let i=0;i<16;i++){const x=rand()*1024,y=rand()*1024,r=20+rand()*90,g=wg.createRadialGradient(x,y,1,x,y,r);g.addColorStop(0,'rgba(31,29,23,.20)');g.addColorStop(1,'rgba(31,29,23,0)');wg.fillStyle=g;wg.fillRect(x-r,y-r,r*2,r*2);}
  wg.lineWidth=1;wg.strokeStyle='rgba(25,25,23,.3)';for(let i=0;i<9;i++){let x=rand()*1024,y=rand()*1024;wg.beginPath();wg.moveTo(x,y);for(let j=0;j<8;j++){x+=rand()*40-20;y+=rand()*25;wg.lineTo(x,y);}wg.stroke();}wear.update();wear.uScale=wear.vScale=2;floorMat.albedoTexture=wear;
  function add(mesh,m,p,owner=parent,merge=true){mesh.material=m;mesh.position.set(...p);mesh.parent=owner;mesh.receiveShadows=true;mesh.isPickable=false;if(merge)staticMeshes.push(mesh);return mesh;}
  function box(name,size,p,m=paint,owner=parent,merge=true){return add(B.MeshBuilder.CreateBox(name,{width:size[0],height:size[1],depth:size[2]},scene),m,p,owner,merge);}
  // Chamfered hero boxes: six faces, twelve bevels, eight corner triangles.
  function bevel(name,size,p,m=paint,owner=parent,b=.06,merge=true){const h=size.map(x=>x/2),q=h.map(x=>Math.max(.001,x-Math.min(b,Math.min(...h)*.5))),faces=[];
   for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const other=[0,1,2].filter(x=>x!==axis);faces.push([[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,c])=>{const point=[0,0,0];point[axis]=h[axis]*sign;point[other[0]]=q[other[0]]*a;point[other[1]]=q[other[1]]*c;return point;}));}
   for(let a=0;a<3;a++)for(let c=a+1;c<3;c++)for(const sa of [-1,1])for(const sc of [-1,1]){const free=3-a-c;faces.push([[true,-1],[false,-1],[false,1],[true,1]].map(([outer,side])=>{const p=[0,0,0];p[a]=(outer?h[a]:q[a])*sa;p[c]=(outer?q[c]:h[c])*sc;p[free]=q[free]*side;return p;}));}
   for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1])faces.push([0,1,2].map(axis=>[0,1,2].map(i=>(i===axis?h[i]:q[i])*[x,y,z][i])));
   const positions=[],indices=[],normals=[],uvs=[];for(const face of faces){const ab=v(...face[1]).subtract(v(...face[0])),ac=v(...face[2]).subtract(v(...face[0]));if(B.Vector3.Dot(B.Vector3.Cross(ab,ac),v(...face[0]))<0)face.reverse();const start=positions.length/3;for(let i=0;i<face.length;i++){positions.push(...face[i]);uvs.push(i===1||i===2?1:0,i>=2?1:0);}for(let i=1;i<face.length-1;i++)indices.push(start,start+i+1,start+i);}B.VertexData.ComputeNormals(positions,indices,normals);const mesh=new B.Mesh(name,scene),data=new B.VertexData();Object.assign(data,{positions,indices,normals,uvs});data.applyToMesh(mesh);return add(mesh,m,p,owner,merge);}
  function cylinder(name,radius,height,p,m=steel,owner=parent,segments=12,merge=true){return add(B.MeshBuilder.CreateCylinder(name,{height,diameter:radius*2,tessellation:segments},scene),m,p,owner,merge);}
  function tube(name,points,radius,m=dark){return add(B.MeshBuilder.CreateTube(name,{path:points.map(a=>v(...a)),radius,tessellation:6},scene),m,[0,0,0]);}
  function sign(name,text,p,w=2,h=.6,mcolor='#6dbea9'){const t=new B.DynamicTexture(name,{width:512,height:128},scene,false);textures.push(t);const g=t.getContext();g.fillStyle='#132228';g.fillRect(0,0,512,128);g.strokeStyle=mcolor;g.lineWidth=4;g.strokeRect(8,8,496,112);g.fillStyle=mcolor;g.font='bold 25px monospace';g.textAlign='center';g.fillText(text,256,72);t.update();const m=new B.StandardMaterial(name,scene);owned.push(m);m.diffuseTexture=t;m.emissiveTexture=t;m.specularColor=B.Color3.Black();const mesh=B.MeshBuilder.CreatePlane(name,{width:w,height:h,sideOrientation:B.Mesh.DOUBLESIDE},scene);add(mesh,m,p,parent,false);return mesh;}
  function hook(id,at,fallback){const imported=VoidAssets.instance('opening:'+id,parent);if(imported){imported.position.set(...at);return imported;}return fallback();}
  const ground=add(B.MeshBuilder.CreateGround('vesper-terrain',{width:1600,height:1600,subdivisions:1},scene),sand,[0,-.07,0],parent,false);
  const sky=new B.ShaderMaterial('ward-sky',scene,{vertexSource:'precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;varying vec3 p;void main(){p=position;gl_Position=worldViewProjection*vec4(position,1.);}',fragmentSource:'precision highp float;varying vec3 p;void main(){float h=clamp(normalize(p).y,0.,1.);vec3 c=mix(vec3(.60,.73,.81),vec3(.10,.33,.65),pow(h,.45));gl_FragColor=vec4(c,1.);}'},{attributes:['position'],uniforms:['worldViewProjection']});owned.push(sky);sky.backFaceCulling=false;sky.disableDepthWrite=true;
  const dome=B.MeshBuilder.CreateSphere('vesper-sky',{diameter:1900,segments:16,sideOrientation:B.Mesh.BACKSIDE},scene);add(dome,sky,[0,0,0],parent,false);dome.infiniteDistance=true;
  scene.clearColor=B.Color4.FromHexString('#9aaab9ff');scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.00125;scene.fogColor=B.Color3.FromHexString('#c9b99e');scene.ambientColor=B.Color3.Black();
  const hemi=scene.lights.find(l=>l.name==='ambient');if(hemi){hemi.intensity=.38;hemi.diffuse=B.Color3.FromHexString('#b7d3ec');hemi.groundColor=B.Color3.FromHexString('#a78461');}shadowLight.direction=v(-.55,-.8,.25);shadowLight.intensity=2.2;shadowLight.diffuse=B.Color3.FromHexString('#ffe0ad');shadowLight.position=v(45,75,-30);shadowLight.shadowMinZ=1;shadowLight.shadowMaxZ=180;shadowLight.autoUpdateExtends=false;shadowLight.orthoLeft=-65;shadowLight.orthoRight=65;shadowLight.orthoBottom=-65;shadowLight.orthoTop=65;
  scene.imageProcessingConfiguration.toneMappingEnabled=true;scene.imageProcessingConfiguration.exposure=1.05;scene.imageProcessingConfiguration.contrast=1.12;
  // Broad, simple terrain silhouettes form a deep horizon without large texture downloads.
  const rock=mat('mesa','#966f51');for(let i=0;i<24;i++){const angle=i/24*Math.PI*2,d=350+rand()*320,h=12+rand()*30,r=25+rand()*40;const mesh=B.MeshBuilder.CreateCylinder('distant-mesa',{height:h,diameterTop:r*.9,diameterBottom:r*1.65,tessellation:5},scene);add(mesh,rock,[Math.sin(angle)*d,h*.44-3,Math.cos(angle)*d]);mesh.rotation.y=rand()*4;}
  const moonMat=mat('moon','#d8d9d2',1,0,'#33393d');const moon=add(B.MeshBuilder.CreateSphere('distant-moon',{diameter:80,segments:24},scene),moonMat,[330,160,700],parent,false);moon.receiveShadows=false;
  // Independent open-front workshop; no station shell, solar arrays or interior corridor.
  hook('workshop',[0,0,0],()=>{box('workshop-slab',[29,.25,28],[0,-.1,-10],floorMat);for(const x of [-13,13]){bevel('wall-panel',[.35,6,24],[x,3,-11.5]);for(let z=-21;z<1;z+=4)bevel('support-column',[.42,6.2,.5],[x*.97,3.1,z],steel);}
   box('back-panel',[26,6,.35],[0,3,-23],paint);box('garage-roof',[28,.28,25],[0,6.2,-11.5],steel);bevel('header',[27,.6,.65],[0,5.8,.5],rust);for(let z=-21;z<2;z+=4){bevel('roof-crossbeam',[26,.22,.22],[0,5.8,z],steel);for(const x of [-8,8]){const beam=bevel('diagonal-brace',[.16,.16,6],[x,5.4,z+1],steel);beam.rotation.z=x<0?.08:-.08;}}
   for(const x of [-12,12]){bevel('door-track',[.22,5.8,.25],[x,2.9,.9],dark);for(let y=1;y<5;y+=1.2)bevel('panel-repair',[.06,.8,1.4],[x>0?12.78:-12.78,y,-14],y%2?paint:steel);}
   for(const x of [-8,7])for(const z of [-6,-17]){bevel('light-fixture',[2.8,.16,.35],[x,5.9,z],dark);box('warm-strip',[2.5,.04,.2],[x,5.79,z],warm);}return parent;});
  const lamp=new B.PointLight('ward-worklamp',v(-7,3,-6),scene);lamp.diffuse=B.Color3.FromHexString('#ffc57c');lamp.intensity=45;lamp.range=12;lamp.parent=parent;
  // Workbench, drawers, diagnostic screen and restrained tool silhouettes.
  hook('bench',[-10,0,-11],()=>{bevel('bench-top',[2.5,.18,8],[-10,1.03,-11],steel);for(const z of [-14,-8]){bevel('cabinet',[2.25,.95,2.6],[-10,.5,z],rust);for(let i=0;i<4;i++){bevel('drawer',[2.05,.16,.035],[-10,.22+i*.2,z+1.32],paint);bevel('drawer-handle',[.65,.045,.07],[-10,.22+i*.2,z+1.36],steel);}}for(let i=0;i<8;i++){const tool=bevel('bench-tool',[.12,.05,.45],[-10.8+rand()*1.4,1.16,-13+rand()*4],steel);tool.rotation.y=rand()*5;}return parent;});
  bevel('diagnostic-case',[1.8,1.2,.22],[-10,2,-13.7],rust);sign('diagnostic','KESTREL / SYSTEMS NOMINAL',[-10,2,-13.55],1.5,.85,'#69b9cc');
  for(let i=0;i<3;i++){bevel('service-case',[1.3,.7,1],[-11+i*1.7,.38,-20],i===1?steel:rust);bevel('case-lid',[1.34,.1,1.05],[-11+i*1.7,.79,-20],paint);}
  for(const z of [-18,-15]){cylinder('gas-bottle',.23,1.35,[9.6,.75,z],z===-18?rust:blue);cylinder('valve',.07,.14,[9.6,1.49,z],steel);}
  const hose=[];for(let i=0;i<48;i++){const a=i*.19;hose.push([-5+Math.cos(a)*(1.2-i*.008),.08,-14+Math.sin(a)*(1.2-i*.008)]);}tube('coiled-service-hose',hose,.045);tube('power-cable',[[-10,.09,-11],[-7,.09,-10],[-5,.09,-7],[-6,.09,-4]],.035);
  for(const x of [8.2,10.2])bevel('hoist-upright',[.18,3.2,.18],[x,1.6,-17],rust);bevel('hoist-crossbar',[2.6,.22,.3],[9.2,3.2,-17],rust);cylinder('hoist-cable',.018,1.3,[9.2,2.45,-17],steel);const hookRing=B.MeshBuilder.CreateTorus('hoist-hook',{diameter:.3,thickness:.06,tessellation:12},scene);add(hookRing,steel,[9.2,1.7,-17]);hookRing.rotation.x=Math.PI/2;
  // Useful workshop clutter stays along the sides, leaving a clear walking lane.
  for(let i=0;i<5;i++){bevel('tool-drawer',[1.3,.16,.05],[-10.3,.25+i*.14,-6.6],paint);bevel('tool-pull',[.6,.035,.09],[-10.3,.25+i*.14,-6.54],steel);}
  cylinder('shop-stool-seat',.4,.13,[-7.8,.86,-10],dark);for(const x of [-8,-7.6])for(const z of [-10.2,-9.8])cylinder('stool-leg',.035,.8,[x,.4,z],steel);
  for(let i=0;i<5;i++)bevel('floor-expansion-joint',[25,.012,.025],[0,.036,-20+i*4.5],dark);
  for(let i=0;i<55;i++)box('drain-slot',[.08,.016,.5],[-11+i*.4,.045,.6],dark);
  for(let i=0;i<10;i++){const z=-18+i*1.7;bevel('electrical-conduit',[.045,.045,1.55],[-12.7,2.4,z],steel);}
  for(let i=0;i<22;i++){const x=rand()*80-40,z=5+rand()*65;if(Math.abs(x-12)<14&&Math.abs(z-25)<15||Math.abs(x)<16&&z<10)continue;const stone=B.MeshBuilder.CreatePolyhedron('apron-stone',{type:1,size:.12+rand()*.3},scene);add(stone,rock,[x,.08,z]);stone.scaling.y=.5;}
  // Landing apron and maintained, older Kestrel. A single hook owns its replacement.
  box('landing-pad',[22,.12,24],[12,-.005,25],floorMat);for(const x of [2,22])for(let z=16;z<36;z+=3)box('pad-stripe',[.18,.025,1.8],[x,.07,z],rust);
  const ship=hook('kestrel',[12,1.8,25],()=>{const n=shipModel('starter','friendly',parent);n.position.set(12,2,25);n.scaling.set(2.4,2.4,2.8);n.rotation.y=Math.PI+.4;return n;});
  for(const x of [8.5,15.5])for(const z of [21,29]){cylinder('landing-leg',.1,1.5,[x,.78,z]);bevel('landing-foot',[.75,.12,1],[x,.1,z],dark);}
  for(let i=0;i<5;i++)bevel('boarding-step',[2,.14,.55],[5.5+i*.3,.13+i*.22,24],steel);
  for(const x of [-3,2])cylinder('sign-hanger',.015,.6,[x,5.5,.86],steel);
  sign('workshop-name','WARD REPAIR / INDEPENDENT',[-.8,4.8,.86],7,.8,'#dbbf85');
  cylinder('fuel-drum',2.1,3.5,[-22,1.75,14],paint, parent,16);cylinder('fuel-cap',.6,.2,[-22,3.55,14],steel);tube('fuel-hose',[[-22,.08,16],[-18,.08,20],[-16,.08,23]],.09);
  // Sparse occupied settlement and one distant technology accent.
  for(let i=0;i<7;i++){const x=-48-(i%3)*16,z=26+Math.floor(i/3)*20,w=8+rand()*4;bevel('settlement-module',[w,4,9],[x,2,z],i%2?paint:floorMat,parent,.25);const roof=B.MeshBuilder.CreateCylinder('settlement-roof',{height:9,diameter:4,tessellation:12},scene);add(roof,paint,[x,4,z]);roof.rotation.x=Math.PI/2;for(let j=0;j<2;j++)box('settlement-window',[1.2,.7,.04],[x-2+j*3,2.5,z+4.55],blue);}
  for(const x of [-35,45]){cylinder('antenna-mast',.10,13,[x,6.5,45],steel);for(let y=4;y<12;y+=3)bevel('antenna-panel',[.7,1.3,.1],[x,y,45],paint);}
  sign('distant-ad','TRANSIT / REPAIR / FUEL',[-54,6,36],5,1.5,'#72a7c5');
  // Shooting lane faces away from settlement and landing pad, into a dirt backstop.
  const berm=B.MeshBuilder.CreateCylinder('range-berm',{height:7,diameterTop:4,diameterBottom:12,tessellation:8},scene);add(berm,rock,[47,2,-8]);berm.scaling.z=2.8;
  bevel('target-shelf',[1,.2,14],[39,1.02,-8],steel);for(const z of [-14,-2])bevel('rack-leg',[.16,1,.16],[39,.5,z],rust);
  for(const def of VoidOpening.cans){const node=new B.TransformNode('can-'+def.id,scene);node.parent=parent;node.position.set(...def.position);const body=cylinder('can-body-'+def.id,.14,.44,[0,0,0],def.id%2?paint:rust,node,12,false);body.isPickable=true;body.metadata={canId:def.id};cylinder('can-rim',.145,.025,[0,.23,0],steel,node,12,false);cylinder('can-rim',.145,.025,[0,-.23,0],steel,node,12,false);canNodes.push({id:def.id,node,body,velocity:null,spin:0,base:def.position.slice()});if(state.progression.opening?.cans.includes(def.id)){node.position.y=.2;node.rotation.z=1.3;body.isPickable=false;}}
  sign('range-note','KEEP FIRE TOWARD BERM',[36,1.5,-16],3,.55,'#c6b480').rotation.y=-Math.PI/2;
  // Mara is the only person here. Rounded primitives improve the interim silhouette.
  const mara=hook('mara',[7,0,-5],()=>{const n=characterModel('mara',parent,[7,0,-5]);for(const mesh of n.getChildMeshes())if(/arm|leg|torso|coat|hair/.test(mesh.name)){mesh.isVisible=false;}bevel('mara-jacket',[.49,.63,.28],[0,1.1,0],cloth,n,.12,false);bevel('mara-hem',[.53,.25,.31],[0,.77,0],cloth,n,.07,false);for(const side of [-1,1]){const arm=cylinder('mara-arm',.085,.56,[side*.32,1.12,0],cloth,n,10,false);arm.rotation.z=side*.12;cylinder('mara-leg',.10,.65,[side*.14,.38,0],dark,n,10,false);}const hair=add(B.MeshBuilder.CreateSphere('mara-grey-hair',{diameter:.37,segments:12},scene),mat('grey-hair','#a9aaa1'),[0,1.82,-.045],n,false);hair.scaling.y=.55;const faceMat=mat('mara-skin','#a88870');bevel('mara-nose',[.07,.10,.09],[0,1.70,.19],faceMat,n,.025,false);for(const side of [-1,1]){bevel('mara-eye',[.048,.02,.015],[side*.085,1.75,.171],dark,n,.005,false);bevel('mara-pocket',[.13,.16,.02],[side*.13,1.17,.15],paint,n,.012,false);}bevel('mara-belt',[.48,.055,.32],[0,.84,0],dark,n,.01,false);return n;});mara.rotation.y=Math.PI;
  // Elias is a cyan bust projection above a case, never a physical character actor.
  bevel('projector-case',[1.8,.8,1.2],[-6,.43,-3],rust);bevel('projector-top',[1.9,.12,1.25],[-6,.9,-3],steel);sign('archive-label','ELIAS WARD / RECORDING',[-6,.68,-2.37],1.5,.28,'#77c6dc');
  const holoMaterial=new B.ShaderMaterial('elias-projection',scene,{vertexSource:'precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;uniform mat4 world;varying vec3 p;void main(){p=(world*vec4(position,1.)).xyz;gl_Position=worldViewProjection*vec4(position,1.);}',fragmentSource:'precision highp float;varying vec3 p;uniform float time;void main(){float scan=.75+.25*sin(p.y*160.+time*2.);float flicker=.93+.07*sin(time*17.);gl_FragColor=vec4(vec3(.18,.68,.94)*scan,.30*flicker);}'},{attributes:['position'],uniforms:['worldViewProjection','world','time'],needAlphaBlending:true});owned.push(holoMaterial);holoMaterial.backFaceCulling=false;
  const hologram=hook('elias',[-6,1.1,-3],()=>{const n=new B.TransformNode('elias-hologram',scene);n.parent=parent;n.position.set(-6,1.1,-3);const bust=add(B.MeshBuilder.CreateSphere('projection-shoulders',{diameter:1,segments:16},scene),holoMaterial,[0,.24,0],n,false);bust.scaling.set(.75,.6,.37);const head=add(B.MeshBuilder.CreateSphere('projection-head',{diameter:.43,segments:20},scene),holoMaterial,[0,.79,0],n,false);head.scaling.set(1,1.25,.92);for(const side of [-1,1]){bevel('projection-brow',[.16,.035,.05],[side*.11,.89,.19],holoMaterial,n,.015,false);bevel('projection-eye',[.075,.028,.03],[side*.1,.835,.212],blue,n,.01,false);}bevel('projection-nose',[.065,.13,.085],[0,.78,.24],holoMaterial,n,.025,false);for(let i=-2;i<=2;i++){const beard=add(B.MeshBuilder.CreateSphere('projection-beard',{diameter:.12,segments:8},scene),holoMaterial,[i*.052,.62-Math.abs(i)*.01,.16],n,false);beard.scaling.y=1.25;}for(let i=0;i<9;i++){const a=i/9*Math.PI*2;add(B.MeshBuilder.CreateSphere('projection-hair',{diameter:.14,segments:8},scene),holoMaterial,[Math.cos(a)*.18,1.02+Math.sin(a)*.055,Math.sin(a)*.12-.05],n,false);}return n;});
  hologram.rotation.y=Math.PI;
  for(const mesh of hologram.getChildMeshes()){mesh.material=holoMaterial;mesh.isPickable=false;mesh.receiveShadows=false;}
  const cone=B.MeshBuilder.CreateCylinder('projection-cone',{height:.9,diameterTop:.85,diameterBottom:.08,tessellation:20},scene);add(cone,holoMaterial,[-6,1.4,-3],parent,false);
  // Merge repeated static scenery by material; dynamic actors/targets stay independent.
  for(const m of Object.values(mats)){const batch=staticMeshes.filter(mesh=>mesh.material===m&&mesh.parent===parent&&Math.hypot(mesh.position.x,mesh.position.z)<80);if(batch.length>1){const merged=B.Mesh.MergeMeshes(batch,true,true,undefined,false,true);if(merged){merged.parent=parent;merged.receiveShadows=true;merged.isPickable=false;}}}
  let shadow;if(!low){shadow=new B.ShadowGenerator(quality==='high'?2048:1024,shadowLight);shadow.usePercentageCloserFiltering=true;shadow.filteringQuality=B.ShadowGenerator.QUALITY_LOW;shadow.bias=.003;shadow.normalBias=.08;shadowLight.autoCalcShadowZBounds=false;for(const mesh of parent.getChildMeshes())if(mesh!==ground&&mesh!==dome&&mesh.material!==holoMaterial&&mesh!==moon&&Math.hypot(mesh.position.x,mesh.position.z)<80&&mesh.getTotalVertices()>0)shadow.addShadowCaster(mesh,false);}
  const dust=new B.ParticleSystem('workshop-dust',low?24:60,scene);const dot=new B.DynamicTexture('dust-dot',16,scene,false);textures.push(dot);let dc=dot.getContext();dc.clearRect(0,0,16,16);const grad=dc.createRadialGradient(8,8,0,8,8,8);grad.addColorStop(0,'#fff');grad.addColorStop(1,'rgba(255,255,255,0)');dc.fillStyle=grad;dc.fillRect(0,0,16,16);dot.update();dust.particleTexture=dot;dust.emitter=v(0,1,2);dust.minEmitBox=v(-14,0,-10);dust.maxEmitBox=v(14,4,16);dust.color1=new B.Color4(.8,.65,.42,.09);dust.color2=new B.Color4(.9,.8,.6,.04);dust.colorDead=new B.Color4(.9,.8,.6,0);dust.minSize=.035;dust.maxSize=.09;dust.minLifeTime=5;dust.maxLifeTime=10;dust.emitRate=low?2:5;dust.direction1=v(.1,.01,.03);dust.direction2=v(.25,.05,.08);dust.minEmitPower=.1;dust.maxEmitPower=.3;dust.gravity=v(0,0,0);dust.start();
  const weaponRoot=new B.TransformNode('ward-first-person',scene);weaponRoot.parent=camera;
  const importedPistol=VoidAssets.instance('opening:pistol',weaponRoot);
  if(!importedPistol){bevel('pistol-slide',[.065,.085,.29],[0,0,0],steel,weaponRoot,.012,false);bevel('pistol-grip',[.058,.14,.08],[0,-.085,-.07],dark,weaponRoot,.014,false);bevel('pistol-front-sight',[.012,.014,.018],[0,.048,.12],rust,weaponRoot,.004,false);bevel('pistol-rear-sight',[.06,.02,.022],[0,.05,-.105],dark,weaponRoot,.005,false);}
  for(const mesh of weaponRoot.getChildMeshes()){mesh.renderingGroupId=1;mesh.isPickable=false;mesh.receiveShadows=false;}weaponRoot.setEnabled(false);
  let leadIndex=state.progression.opening?.pistol?3:-1;const route=[[7,0,4],[20,0,4],[24,0,-8]];
  if(leadIndex===3)mara.position.set(24,0,-8);
  let lastTime=null;const handle={root:parent,mara,hologram,canNodes,ship,
   lead(){leadIndex=0;},
   weapon(drawn,aim,reloading){weaponRoot.setEnabled(drawn);weaponRoot.position.set(aim?0:.21,reloading?-.40:aim?-.07:-.23,aim?.5:.55);weaponRoot.rotation.set(reloading?.65:0,0,reloading?.4:0);camera.metadata={...camera.metadata,openingAim:aim};},
   hit(id,direction){const can=canNodes.find(c=>c.id===id);if(!can||can.velocity)return;can.velocity=v(direction.x*2.6,1.8,direction.z*2.6);can.spin=6;can.body.isPickable=false;},
   tick(time){const dt=lastTime===null?0:Math.min(.05,Math.max(0,time-lastTime));lastTime=time;if(leadIndex>=0&&leadIndex<route.length){const target=v(...route[leadIndex]),delta=target.subtract(mara.position),distance=delta.length();if(distance<.12)leadIndex++;else if(B.Vector3.Distance(camera.position,mara.position)<16){mara.position.addInPlace(delta.scale(Math.min(distance,dt*1.6)/distance));mara.rotation.y=Math.atan2(delta.x,delta.z);}}
    holoMaterial.setFloat('time',time);hologram.scaling.y=1+Math.sin(time*19)*.003;for(const c of canNodes)if(c.velocity){c.velocity.y-=9.8*dt;c.node.position.addInPlace(c.velocity.scale(dt));c.node.rotation.z+=c.spin*dt;c.node.rotation.x+=c.spin*.4*dt;if(c.node.position.y<.15){c.node.position.y=.15;c.velocity.y=Math.abs(c.velocity.y)*.18;c.velocity.x*=Math.exp(-7*dt);c.velocity.z*=Math.exp(-7*dt);c.spin*=Math.exp(-5*dt);if(Math.hypot(c.velocity.x,c.velocity.z)<.04&&c.velocity.y<.3)c.velocity=null;}}},
   dispose(){weaponRoot.dispose();shadow?.dispose();dust.dispose();for(const t of textures)t.dispose();for(const m of owned)m.dispose(false,false);scene.fogMode=B.Scene.FOGMODE_NONE;scene.imageProcessingConfiguration.toneMappingEnabled=false;scene.imageProcessingConfiguration.exposure=1;scene.imageProcessingConfiguration.contrast=1;scene.ambientColor=B.Color3.Black();if(hemi){hemi.intensity=.48;hemi.diffuse=B.Color3.White();hemi.groundColor=new B.Color3(.12,.15,.21);}shadowLight.autoUpdateExtends=true;shadowLight.orthoLeft=shadowLight.orthoRight=shadowLight.orthoTop=shadowLight.orthoBottom=null;shadowLight.position=v(0,0,0);shadowLight.intensity=1.5;shadowLight.diffuse=B.Color3.White();shadowLight.direction=v(.6,-.7,.4);}
  };return handle;
 }
 root.VoidOpeningScene={build};
})(globalThis);
