/* Disposable FPS Skirmish: no Campaign state writer or save path. */
(function(root){
 const station=VoidDerelictStation,layout=station.layout;
 const tuning={easy:{damage:7,accuracy:.46,reaction:1.5,speed:.8},normal:{damage:11,accuracy:.66,reaction:1.1,speed:1.05},hard:{damage:15,accuracy:.82,reaction:.7,speed:1.3}};
 let choice={type:'fps',location:'derelict-station',difficulty:'normal'},match=null,generation=0;
 const keys=new Set(),hud=document.createElement('div');hud.id='skirmish-hud';hud.hidden=true;document.body.append(hud);
 function snapshot(){return JSON.stringify({location:state.location,credits:state.credits,quest:state.quest,progression:state.progression,story:state.story,inventory:state.inventory,savedAt:state.savedAt});}
 function verify(original){if(original!==snapshot())console.error('[SKIRMISH] Campaign state changed during isolated match');}
 function setup(){if(match)end();VoidMenu.returnTo=null;showSetup();}
 function showSetup(){let choices=['fps','flight'].map(v=>button(v.toUpperCase(),'skirmish-type:'+v,choice.type!==v)).join('');let fps='<h2>LOCATION</h2><p class="skirmish-location">DERELICT SPACE STATION</p><h2>ENEMY DIFFICULTY</h2><div class="skirmish-choices">'+Object.keys(tuning).map(v=>button(v.toUpperCase(),'skirmish-difficulty:'+v,choice.difficulty!==v)).join('')+'</div>'+button('ENTER SKIRMISH','skirmish-enter');menuShell('skirmish','<section class="settings-panel skirmish-menu"><p class="menu-kicker">VOID//RUNNER / SINGLE-PLAYER SIMULATION</p><h1 tabindex="-1">SKIRMISH</h1><p>Match resources and damage are temporary. Campaign progress is untouched.</p><h2>COMBAT TYPE</h2><div class="skirmish-choices">'+choices+'</div>'+(choice.type==='fps'?fps:'<p class="fine">Flight Skirmish is not available in this build. Campaign flight remains available.</p>')+button('MAIN MENU','skirmish-main',true)+'</section>');}
 function end(invalidate=true){if(invalidate)generation++;if(match){verify(match.original);match.enemies.forEach(e=>{e.node?.dispose();e.material?.dispose();e.visor?.dispose();});match=null;}keys.clear();hud.hidden=true;document.body.classList.remove('skirmish-active');document.exitPointerLock?.();VoidBabylon.release();}
 function main(){end();VoidMenu.returnTo=null;renderMainMenu();}
 function blocked(x,z){return VoidExplorer.blocked(x,z,layout);}
 function visible(a,b){const dx=b.x-a.x,dz=b.z-a.z,n=Math.hypot(dx,dz);for(let t=.5;t<n-.5;t+=.4)if(blocked(a.x+dx*t/n,a.z+dz*t/n))return false;return true;}
 function route(from,to){const step=1.5,minX=-37,minZ=-76,w=50,h=120,ix=x=>Math.max(0,Math.min(w-1,Math.round((x-minX)/step))),iz=z=>Math.max(0,Math.min(h-1,Math.round((z-minZ)/step))),cell=(x,z)=>z*w+x,start=cell(ix(from.x),iz(from.z)),goal=cell(ix(to.x),iz(to.z)),prev=new Int32Array(w*h).fill(-1),queue=[start];prev[start]=start;
  for(let i=0;i<queue.length&&i<6000;i++){const n=queue[i];if(n===goal)break;const x=n%w,z=Math.floor(n/w);for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,zz=z+dz,k=cell(xx,zz);if(xx<0||xx>=w||zz<0||zz>=h||prev[k]>=0||blocked(minX+xx*step,minZ+zz*step))continue;prev[k]=n;queue.push(k);}}
  if(prev[goal]<0)return [];const result=[];for(let n=goal;n!==start&&result.length<150;n=prev[n])result.push({x:minX+(n%w)*step,z:minZ+Math.floor(n/w)*step});return result.reverse();
 }
 function spawn(s){const B=BABYLON,scene=VoidBabylon.scene;let id=0;
  for(const zone of station.zones)for(const [x,z,level=0] of zone.enemies){const e={id:id++,zone:zone.id,x,z,level,hp:zone.id==='stronghold'?70:54,dead:false,alert:false,fire:1.4,flank:id%2?1:-1,routeTimer:0,path:[]};const node=new B.TransformNode('derelict-raider-'+e.id,scene),mat=new B.PBRMaterial('raider-armor-'+e.id,scene);mat.albedoColor=B.Color3.FromHexString(zone.id==='stronghold'?'#6c4444':'#4e5552');mat.metallic=.55;mat.roughness=.82;const visor=new B.StandardMaterial('raider-visor-'+e.id,scene);visor.emissiveColor=B.Color3.FromHexString('#b84439');visor.diffuseColor=B.Color3.FromHexString('#151f23');
   function part(name,shape,size,px,py,pz,m){const mesh=shape==='capsule'?B.MeshBuilder.CreateCapsule(name,{radius:size[0],height:size[1],tessellation:10},scene):shape==='sphere'?B.MeshBuilder.CreateSphere(name,{diameter:1,segments:12},scene):B.MeshBuilder.CreateBox(name,{width:size[0],height:size[1],depth:size[2]},scene);mesh.parent=node;mesh.position.set(px,py,pz);mesh.material=m;mesh.metadata={skirmishEnemy:e.id};return mesh;}
   const torso=part('armored-core','capsule',[.37,.95],0,1.24,0,mat);torso.scaling.z=.72;
   part('angled-chest-plate','box',[.65,.64,.13],0,1.38,.27,mat);part('webbing','box',[.69,.1,.08],0,1.31,.35,visor);
   const helmet=part('sealed-helmet','sphere',[],0,1.96,0,mat);helmet.scaling.set(.27,.29,.29);
   part('visor-slit','box',[.48,.115,.075],0,2,.25,visor);part('respirator','box',[.22,.16,.16],0,1.83,.27,mat);
   for(const side of [-1,1]){const shoulder=part('shoulder-pad','sphere',[],side*.42,1.55,0,mat);shoulder.scaling.set(.23,.19,.24);part('arm','capsule',[.13,.76],side*.46,1.04,.02,mat);part('gauntlet','box',[.29,.22,.31],side*.46,.8,.07,visor);part('thigh','capsule',[.155,.72],side*.22,.58,0,mat);part('knee-pad','box',[.30,.21,.34],side*.22,.48,.14,visor);part('boot','box',[.30,.24,.45],side*.22,.13,.10,mat);}
   part('field-pack','box',[.52,.58,.25],0,1.26,-.36,visor);part('rifle-receiver','box',[.13,.17,.62],.42,.99,.4,visor);part('rifle-barrel','box',[.085,.085,.43],.42,.97,.92,mat);node.position.set(x,level,z);e.node=node;e.material=mat;e.visor=visor;s.enemies.push(e);
  }
 }
 async function start(){if(choice.type!=='fps')return;const token=++generation;if(match)end(false);const original=snapshot();menuShell('skirmish-loading','<section class="settings-panel skirmish-menu"><h1>DERELICT SPACE STATION</h1><p>Opening the hangar…</p></section>');mode='skirmish-loading';
  try{await VoidBabylon.prepareRoom(layout);if(token!==generation)return;match={player:{x:0,y:1.68,z:-71,yaw:0,pitch:0,eye:1.68},health:100,ammo:12,reserve:96,drawn:true,aim:false,reload:0,cooldown:0,grace:3,elapsed:0,kills:0,enemies:[],status:'active',difficulty:choice.difficulty,original};spawn(match);mode='skirmish-fps';view='skirmish';leaveMenu();screen.classList.add('hidden');flightUI(false);hud.hidden=false;document.body.classList.add('skirmish-active');keys.clear();canvas.focus({preventScroll:true});refresh();}
  catch(error){if(token!==generation)return;console.error('[SKIRMISH load]',error);menuShell('skirmish-error','<section class="settings-panel"><h1>STATION UNAVAILABLE</h1><p>'+escapeText(error.message)+'</p>'+button('SKIRMISH SETUP','skirmish-setup',true)+'</section>');verify(original);}
 }
 function outcome(won){if(!match)return;const s=match;s.status=won?'cleared':'defeated';keys.clear();document.exitPointerLock?.();hud.hidden=true;mode='skirmish-result';screen.classList.remove('hidden');const mins=Math.floor(s.elapsed/60),secs=String(Math.floor(s.elapsed%60)).padStart(2,'0');panel('FPS SKIRMISH',won?'DERELICT STATION CLEARED':'SKIRMISH DEFEAT','<p>'+s.difficulty.toUpperCase()+' · '+s.kills+'/'+s.enemies.length+' hostiles defeated · '+mins+':'+secs+'</p><p>Campaign progress is unchanged.</p>',button('RESTART SKIRMISH','skirmish-restart')+button('SKIRMISH SETUP','skirmish-setup',true)+button('MAIN MENU','skirmish-main',true));verify(s.original);}
 function refresh(){if(!match||hud.hidden)return;const s=match,p=s.player,alive=s.enemies.filter(e=>!e.dead),next=alive.reduce((best,e)=>!best||Math.hypot(e.x-p.x,e.z-p.z)<Math.hypot(best.x-p.x,best.z-p.z)?e:best,null),zone=station.zones.reduce((best,z)=>Math.abs(z.z-p.z)<Math.abs(best.z-p.z)?z:best,station.zones[0]);hud.innerHTML='<div class="skirmish-vitals"><b>'+zone.name+'</b><span>HEALTH '+Math.ceil(s.health)+'</span><span>WARD PISTOL '+s.ammo+' / '+s.reserve+(s.reload?' · RELOADING':'')+'</span></div><div class="skirmish-objective">'+(s.grace?'ORIENT YOURSELF · HOSTILES HOLDING FIRE':'CLEAR STATION · '+alive.length+' HOSTILES REMAIN'+(next?' · NEAREST '+Math.round(Math.hypot(next.x-p.x,next.z-p.z))+'m':''))+'</div><div class="skirmish-controls">WASD MOVE · SHIFT RUN · C CROUCH · SPACE JUMP · 1 DRAW · RMB AIM · LMB FIRE · R RELOAD · ESC MENU</div>';}
 function fire(){const s=match;if(!s||s.status!=='active'||!s.drawn||s.reload||s.cooldown||!s.ammo)return;s.ammo--;s.cooldown=.27;const B=BABYLON,p=s.player,dir=new B.Vector3(Math.sin(p.yaw)*Math.cos(p.pitch),-Math.sin(p.pitch),Math.cos(p.yaw)*Math.cos(p.pitch)),hit=VoidBabylon.scene.pickWithRay(new B.Ray(new B.Vector3(p.x,p.y,p.z),dir,65),m=>Number.isInteger(m.metadata?.skirmishEnemy));if(hit?.hit){const e=s.enemies[hit.pickedMesh.metadata.skirmishEnemy];if(e&&!e.dead&&visible(p,e)){e.hp-=s.aim?42:34;e.alert=true;if(e.hp<=0){e.dead=true;e.node.setEnabled(false);s.kills++;if(s.kills===s.enemies.length)outcome(true);}}}VoidAudio.tone(145,.12,'sawtooth',.025);refresh();}
 function step(dt){const s=match;if(!s||s.status!=='active')return;dt=Math.min(.04,dt);s.elapsed+=dt;s.grace=Math.max(0,s.grace-dt);s.cooldown=Math.max(0,s.cooldown-dt);if(s.reload){s.reload=Math.max(0,s.reload-dt);if(!s.reload){const n=Math.min(12-s.ammo,s.reserve);s.ammo+=n;s.reserve-=n;}}
  const p=s.player;VoidExplorer.step(p,{x:FM.clamp(Number(keys.has('KeyD'))-Number(keys.has('KeyA'))+VoidInput.axes.moveX,-1,1),z:FM.clamp(Number(keys.has('KeyW'))-Number(keys.has('KeyS'))+VoidInput.axes.moveZ,-1,1),crouch:keys.has('KeyC')||keys.has('ControlLeft')||VoidInput.virtual.has('crouch'),run:keys.has('ShiftLeft')||VoidInput.virtual.has('sprint')},dt,layout);const ramp=Math.abs(p.x)>13&&Math.abs(p.x)<17&&p.z>-71&&p.z<-27?Math.min(4.5,Math.max(0,(p.z+71)*.56)):0;p.y=p.eye+ramp+(p.height||0);const tune=tuning[s.difficulty];
  for(const e of s.enemies){if(e.dead)continue;const dx=p.x-e.x,dz=p.z-e.z,distance=Math.hypot(dx,dz),line=distance<29&&visible(e,p);if(line)e.alert=true;if(distance>42||!e.alert)continue;e.fire-=dt;
   if(!e.level&&distance>5&&distance<30){let goal=p;if(!line){e.routeTimer-=dt;if(e.routeTimer<=0){e.path=route(e,p);e.routeTimer=1.8+e.id*.03;}while(e.path.length&&Math.hypot(e.path[0].x-e.x,e.path[0].z-e.z)<.8)e.path.shift();if(e.path.length)goal=e.path[0];}const tx=goal.x-e.x,tz=goal.z-e.z,len=Math.hypot(tx,tz)||1;let mx=tx/len,mz=tz/len;if(line&&distance<12){mx=-mx*.3+e.flank*mz*.8;mz=-mz*.3-e.flank*dx/distance*.8;}const speed=tune.speed*dt;if(!blocked(e.x+mx*speed,e.z))e.x+=mx*speed;if(!blocked(e.x,e.z+mz*speed))e.z+=mz*speed;}
   e.node.position.set(e.x,e.level,e.z);e.node.rotation.y=Math.atan2(dx,dz);if(!s.grace&&line&&distance<24&&e.fire<=0){e.fire=tune.reaction+Math.random()*.8;if(Math.random()<tune.accuracy){s.health=Math.max(0,s.health-tune.damage);hud.classList.add('hit');setTimeout(()=>hud.classList.remove('hit'),180);if(s.health<=0){outcome(false);return;}}}}if(Math.floor(s.elapsed*4)!==Math.floor((s.elapsed-dt)*4))refresh();
 }
 const oldUpdate=update,oldDraw=draw,oldMenu=openGameMenu;
 update=function(dt){if(mode==='skirmish-fps'){step(dt);return;}if(mode==='skirmish-loading'||mode==='skirmish-result')return;oldUpdate(dt);};
 draw=function(){if(mode==='skirmish-fps'||mode==='skirmish-result'){const s=match;if(s){const image=VoidBabylon.renderRoom(s.player,W,H,s.elapsed);if(image)ctx.drawImage(image,0,0,W,H);if(mode==='skirmish-fps'){ctx.strokeStyle=s.aim?'#ef7470':'#e8ddd0';ctx.lineWidth=2;ctx.beginPath();for(const [x,y] of [[-7,0],[3,0],[0,-7],[0,3]]){ctx.moveTo(W/2+x,H/2+y);ctx.lineTo(W/2+x+(x?4:0),H/2+y+(y?4:0));}ctx.stroke();}}return;}if(mode==='skirmish-loading'){ctx.fillStyle='#07101a';ctx.fillRect(0,0,W,H);return;}oldDraw();};
 openGameMenu=function(){if(mode==='skirmish-fps'){keys.clear();document.exitPointerLock?.();hud.hidden=true;VoidMenu.returnTo=()=>{mode='skirmish-fps';screen.classList.add('hidden');leaveMenu();hud.hidden=false;canvas.focus({preventScroll:true});};menuShell('skirmish-pause','<section class="settings-panel skirmish-menu"><h1>SKIRMISH PAUSED</h1>'+button('RESUME','menu-resume')+button('SETTINGS','menu-settings',true)+button('RESTART','skirmish-restart')+button('SKIRMISH SETUP','skirmish-setup',true)+button('MAIN MENU','skirmish-main',true)+'</section>');return;}oldMenu();};
 function action(id,held=false){if(!match||mode!=='skirmish-fps')return;if(id==='fire'){if(held)fire();return;}if(id==='aim'){match.aim=held;return;}if(!held)return;if(id==='jump')match.player.jumpRequested=true;else if(id==='reload'&&!match.reload&&match.reserve>0&&match.ammo<12)match.reload=1.35;else if(id==='draw')match.drawn=!match.drawn;}
 root.VoidSkirmish={setup,start,end,action,get active(){return match;},get selection(){return {...choice};},difficulty:tuning};
 document.addEventListener('click',e=>{const a=e.target.closest('button')?.dataset.action;if(!a)return;if(a==='skirmish-main')main();else if(a==='skirmish-setup'){end();showSetup();}else if(a==='skirmish-enter'||a==='skirmish-restart')start();else if(a.startsWith('skirmish-type:')){choice.type=a.split(':')[1];showSetup();}else if(a.startsWith('skirmish-difficulty:')){choice.difficulty=a.split(':')[1];showSetup();}});
 addEventListener('keydown',e=>{if(mode!=='skirmish-fps'||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','ShiftLeft','KeyC','ControlLeft','Space','KeyR','Digit1'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyR'&&match&&!match.reload&&match.reserve>0&&match.ammo<12)match.reload=1.35;if(e.code==='Digit1'&&match)match.drawn=!match.drawn;if(e.code==='Space'&&match)match.player.jumpRequested=true;});addEventListener('keyup',e=>keys.delete(e.code));
 addEventListener('blur',()=>{keys.clear();if(mode==='skirmish-fps')openGameMenu();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='skirmish-fps')openGameMenu();});
 canvas.addEventListener('click',()=>{if(mode==='skirmish-fps'&&root.VoidControls?.deviceClass!=='touch-first')canvas.requestPointerLock?.()?.catch?.(()=>{});});canvas.addEventListener('mousedown',e=>{if(mode!=='skirmish-fps'||!match)return;if(e.button===2)match.aim=true;if(e.button===0)fire();});canvas.addEventListener('mouseup',e=>{if(e.button===2&&match)match.aim=false;});canvas.addEventListener('contextmenu',e=>{if(mode==='skirmish-fps')e.preventDefault();});canvas.addEventListener('mousemove',e=>{if(mode!=='skirmish-fps'||!match||document.pointerLockElement!==canvas)return;match.player.yaw+=e.movementX*VoidExplorer.config.sensitivity;match.player.pitch=FM.clamp(match.player.pitch+e.movementY*VoidExplorer.config.sensitivity,-1.25,1.25);});
})(globalThis);
